[Service provider] 'Адміністрування' tab - action buttons
ita-social-projects/OoS-Frontend pull request #1022
Opened 2022-03-29 10:15 UTC by perepichai

Implement the action buttons and status column (UI and logic)

![image](https://user-images.githubusercontent.com/8740198/160589423-c8903584-d33d-4634-a4f9-849f8d099e93.png)

2022-03-29 18:18 UTC, litvinets commented
maybe I am wrong, but right now routing doesn't work, so I cannot go to the pages for review

2022-03-29 18:19 UTC, litvinets requested changes
routing doesn't work

2022-03-30 09:39 UTC, dmitryy90 approved these changes

2022-03-30 09:39 UTC, dmitryy90 commented on src/app/shell/personal-cabinet/provider-admins/provider-admins.component.ts
> +          (user) => user.isDeputy === !!(params.param === 'deputy')
no need to use !!. comparison operator returns boolean

2022-03-30 09:47 UTC, litvinets commented
sorting for other tabs doesn't work 
![image](https://user-images.githubusercontent.com/27493959/160803144-559349d2-b726-4b5d-a545-96ea0f5996f8.png)

2022-03-30 09:51 UTC, litvinets commented
![image](https://user-images.githubusercontent.com/27493959/160803893-cb77c40a-82ea-4bbd-bc5b-2d48acae842a.png)
seems like here is missing something

2022-03-30 09:52 UTC, litvinets commented
I believe that for director it should either have to second step i the form, or add workshops dropdown as well

2022-03-30 09:52 UTC, litvinets approved these changes

2022-03-30 09:52 UTC, litvinets commented on src/app/shell/personal-cabinet/provider-admins/provider-admins.component.ts
>    }
.subscribe((provider: Provider) => this.provider = provider);

2022-03-30 13:15 UTC, merged