#791
ita-social-projects/OoS-Frontend pull request #1027
Opened 2022-03-30 13:32 UTC by LeraKornienko

2022-03-30 15:29 UTC, litvinets requested changes

2022-03-30 15:29 UTC, litvinets commented on src/app/shared/store/admin.state.ts
> +    patchState({
fix spaces

2022-03-30 15:29 UTC, litvinets commented on src/app/shell/admin-tools/platform/create-direction/add-class-form/add-class-form.component.html
> +<form [formGroup]="ClassFormGroup" fxLayout="column" fxLayoutAlign="center space-between" class="step" [ngClass]="(classAmount>1) ? 'step-border' : ''">
[ngClass]="{'step-border': classAmount>1}"

2022-03-30 15:29 UTC, litvinets commented on src/app/shell/admin-tools/platform/create-direction/create-direction.component.ts
> +      });
firstly check for positive result, then do all the following actions 
otherwise we do classes creation but don't dispatch action

2022-03-30 15:29 UTC, litvinets commented on src/app/shell/admin-tools/platform/create-direction/directions/directions.component.html
> +  <app-paginator  [totalEntitiesDir]="(filteredDirections$ | async).totalAmount" [currentPage]="currentPage"
instead totalEntitiesDir use the old vvalue
I don't see why do we need a new input

2022-03-30 15:29 UTC, litvinets commented on src/app/shell/admin-tools/platform/create-direction/directions/directions.component.ts
> +  @Select(AdminState.isLoading)
remove empty lines

2022-03-30 15:29 UTC, litvinets commented on src/app/shell/admin-tools/platform/create-direction/directions/directions.component.ts
> +      .pipe(takeUntil(this.destroy$))
add additional operators such as debounce time and startWith(''),  distinctUntilChanged(),
check it for the search-filed component/city filter, we have the same there

2022-03-30 15:29 UTC, litvinets commented on src/app/shell/admin-tools/platform/create-direction/directions/directions.component.ts
> +
remove empty line

2022-04-01 10:19 UTC, perepichai commented on src/app/shared/components/paginator/paginator.component.ts
> +    return Math.ceil(this.totalEntities / Constants.ITEMS_PER_PAGE) || Math.ceil(this.totalEntitiesDir / Constants.ITEMS_PER_PAGE_DIR);
just as an idea, maybe for getTotalPageAmount method will be good to receive from parent component flag like isDirections and then check and if yes use Constants.ITEMS_PER_PAGE_DIR

2022-04-01 10:19 UTC, perepichai commented on src/app/shared/constants/constants.ts
>    static readonly ITEMS_PER_PAGE = 2 * Math.floor(window.innerWidth / (332));
what do you think is it make sense to use the same approach as with ITEMS_PER_PAGE constant? I mean "2 * Math.floor(window.innerWidth / (332))"

2022-04-06 08:41 UTC, litvinets requested changes

2022-04-06 08:41 UTC, litvinets commented on src/app/shared/enum/modal-confirmation.ts
> +
remove empty line

2022-04-06 08:41 UTC, litvinets commented on src/app/shared/models/category.model.ts
> +
empty line

2022-04-06 08:41 UTC, litvinets commented on src/app/shared/store/admin.state.ts
> +  }
add empty line between methods

2022-04-06 08:41 UTC, litvinets commented on src/app/shared/store/admin.state.ts
> +        }));
```suggestion
        tap((direction: Direction) =>  patchState({ selectedDirection: direction, isLoading: false })));
```

2022-04-06 13:48 UTC, litvinets requested changes

2022-04-06 13:48 UTC, litvinets commented on src/app/shared/components/category-card/category-card.component.ts
> +  @Input() isEditMode: true;
true is not a typo of data:) if you want to set a default value  then it should be @Input() isEditMode = true;
if you want to say the data typo is boolean then you should remain the previous version

2022-04-06 13:48 UTC, litvinets commented on src/app/shared/components/category-card/category-card.component.ts
>    ngOnInit(): void {
you can delete it as well

2022-04-06 13:48 UTC, litvinets commented on src/app/shared/store/admin.state.ts
> +  }
add empty line

2022-04-06 13:48 UTC, litvinets commented on src/app/shared/store/admin.state.ts
> +  }
add empty line

2022-04-06 13:48 UTC, litvinets commented on src/app/shell/admin-tools/platform/create-direction/add-department-form/add-department-form.component.ts
> +      const department = result && new Department(this.departmentFormGroup.value, this.direction.id);
I don think that you should check for result one more time, because you handled it earlier

2022-04-06 13:48 UTC, litvinets commented on src/app/shell/admin-tools/platform/create-direction/directions/directions.component.ts
> +      ).subscribe(() => this.store.dispatch(new GetFilteredDirections()));
don't think you need startWith(''),

2022-04-06 13:48 UTC, litvinets commented on src/app/shell/admin-tools/platform/create-direction/directions/directions.component.ts
> +      .pipe(takeUntil(this.destroy$))
add operators

2022-04-14 09:21 UTC, litvinets approved these changes

2022-04-14 09:22 UTC, litvinets approved these changes

2022-04-18 07:14 UTC, dmitryy90 approved these changes

2022-04-19 14:06 UTC, merged