#930
ita-social-projects/OoS-Frontend pull request #1040
Opened 2022-04-05 13:15 UTC by LeraKornienko

'Редагування закладу' page

2022-04-06 08:43 UTC, litvinets approved these changes

2022-04-06 13:25 UTC, dmitryy90 requested changes

2022-04-06 13:25 UTC, dmitryy90 commented on src/app/shell/personal-cabinet/provider/create-provider/create-photo-form/create-photo-form.component.html
> +    {{PhotoFormGroup.get('description').value.length}}/{{constants.MAX_DESCRIPTION_LENGTH}}</label>
please save description control into the variable and use instead to avoid calling .get() method every second:
eg. {{description.value.length}}

2022-04-20 10:35 UTC, dmitryy90 approved these changes

2022-04-20 10:49 UTC, merged