[personal-cabinet/provider-admins]Show button for deputy/admin creation correctly #1355
ita-social-projects/OoS-Frontend pull request #1356
Opened 2022-06-21 14:22 UTC by Olya-web7

2022-06-21 14:32 UTC, litvinets requested changes

2022-06-21 14:32 UTC, litvinets commented on src/app/shell/personal-cabinet/provider-admins/provider-admins.component.html
> +    <ng-template [ngIf]="btnView == providerAdminRoleUkr.admin && subrole !== Role.ProviderAdmin">
add button on init of this component 
![image](https://user-images.githubusercontent.com/27493959/174825644-ca59d5aa-ce33-4832-812e-ea0ff6abef88.png)

2022-06-22 08:35 UTC, Olya-web7 commented on src/app/shell/personal-cabinet/provider-admins/provider-admins.component.ts
> -      .pipe(takeUntil(this.destroy$))
returned it back)

2022-06-22 08:55 UTC, litvinets approved these changes

2022-06-22 09:38 UTC, merged