paginator
ita-social-projects/OoS-Frontend pull request #1363
Opened 2022-06-22 12:19 UTC by LeraKornienko

2022-06-28 12:21 UTC, litvinets requested changes

2022-06-28 12:21 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/applications.component.html
> +
I see you have added paginator only for parents, move it after the container at the very beginning for both roles

2022-06-28 12:21 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/applications.component.html
> +    <ng-container *ngIf="(applicationCard$ | async)?.length else isEmptyList;">
too much of async, it should be replaced with subscribtion

2022-06-28 12:21 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/applications.component.ts
> +  directionsPerPage$: Observable<number>;
applicationsPerPage$

2022-06-29 06:42 UTC, litvinets requested changes
parent workshops are broken :((( 
![image](https://user-images.githubusercontent.com/27493959/176368316-ecc529f7-b3b2-49ad-8f62-9f6224410961.png)

2022-06-29 06:42 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/applications.component.html
> +  </app-paginator>
let's hide paginator while loading

2022-06-29 06:42 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/applications.component.ts
> +  ngAfterViewInit(): void {}
remove if if it is not needed anymore

2022-06-29 06:42 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/applications.component.ts
> +  applicationCards$: Observable<ApplicationCards>;
there is already select in cabinet-data-component, so you  do not need to copy past it

2022-06-29 06:42 UTC, litvinets commented on src/app/shell/personal-cabinet/parent/children/children.component.html
> +        (deleteChild)="onDelete($event)" [applications]="childApplications(applicationCards$ | async, child)">
this functionality is broken, as I understood it should be entities 
![image](https://user-images.githubusercontent.com/27493959/176368973-8e2f832f-4db4-45d2-ae0d-03b79a4f86bf.png)

2022-06-29 06:48 UTC, litvinets commented
I don't see any changes for displaying the status "isBlocked' in the application card, so I think you forget to add it. I suggest checking *ngIf="application.isBlocked" for this code and id the applications is blocked, then display blocked status and its reason 
![image](https://user-images.githubusercontent.com/27493959/176370133-eca017da-06d4-4b61-903e-8817d92b46c9.png)

2022-06-30 10:23 UTC, Pabloostr approved these changes

2022-07-01 11:01 UTC, litvinets requested changes

2022-07-01 11:01 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/applications.component.ts
> +      this.applicationParams.showBlocked = false;
I belive it is false by default, so you can remove it

2022-07-01 11:15 UTC, litvinets requested changes

2022-07-01 16:56 UTC, litvinets requested changes

2022-07-01 16:56 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.ts
> +    }
remove

2022-07-01 16:56 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.ts
> +  @Output() passApplication = new EventEmitter();
remove

2022-07-01 16:56 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/applications.component.ts
> +
remove

2022-07-01 16:56 UTC, litvinets commented on src/app/shared/components/status-info-card/status-info-card.component.html
> +      <p *ngIf="application.rejectionMessage" class="application-info-menu">{{application.rejectionMessage}}</p>
in ts file     this.status = this.application.isBlocked ? ApplicationStatus.Blocked : ApplicationStatus[this.application.status];

2022-07-01 16:56 UTC, litvinets commented on src/app/shared/store/user.state.ts
> +        patchState(applicationCards ? { applicationCards: applicationCards, isLoading: false } : { filteredWorkshops: {totalAmount: 0, entities: []}, isLoading: false }),));
applicationCards rename state value

2022-07-01 16:56 UTC, litvinets commented on src/app/shell/admin-tools/platform/directions/directions.component.ts
> +    this.store.dispatch(new GetFilteredDirections());
this.store.dispatch([ew SetDirectionsPerPage(itemsPerPage), new GetFilteredDirections()]);

2022-07-01 16:56 UTC, litvinets commented on src/app/shell/personal-cabinet/parent/children/children.component.ts
>    }
call dispatch only once

2022-07-01 16:56 UTC, litvinets commented on src/app/shell/result/workshop-cards-list/workshop-cards-list.component.ts
>    }
same

2022-07-01 16:56 UTC, litvinets commented on src/app/shell/result/workshop-map-view-list/workshop-map-view-list.component.ts
> +    this.store.dispatch(new GetFilteredWorkshops());
same

2022-07-01 20:37 UTC, litvinets approved these changes
finally:)

2022-07-03 20:43 UTC, perepichai approved these changes

2022-07-04 12:58 UTC, merged