Fixed default value in the field Статуc
ita-social-projects/OoS-Frontend pull request #1393
Opened 2022-06-29 08:15 UTC by Illya97

Follow the link: https://github.com/ita-social-projects/OoS-Frontend/issues/1331

2022-06-29 08:47 UTC, litvinets requested changes

2022-06-29 08:47 UTC, litvinets commented on src/app/shell/personal-cabinet/provider/create-provider/create-photo-form/create-photo-form.component.html
> +      <mat-option [value]="0" class="dropdown-option"> Працює </mat-option>
revert this change. we push additional status to have such option ad "відсутній", but with this change, we will have two "працює".  Працює we receive from the back-end and can display it, and add additional status Відсутній.  The lost of options should be remained the same
![image](https://user-images.githubusercontent.com/27493959/176393445-c369152f-938d-4123-82f0-ac6bdd46b0c9.png)

2022-06-29 08:47 UTC, litvinets commented on src/app/shell/personal-cabinet/provider/create-provider/create-photo-form/create-photo-form.component.ts
> +
remove these changes. you should change the default one only 
![image](https://user-images.githubusercontent.com/27493959/176393836-0b9afaed-b5b2-4465-a8cf-e2d6a6026a08.png)

2022-06-29 08:47 UTC, litvinets commented on src/app/shell/personal-cabinet/provider/create-provider/create-photo-form/create-photo-form.component.ts
> +
this is the only change that is needed

2022-06-29 08:47 UTC, litvinets commented on src/app/shell/personal-cabinet/provider/create-provider/create-photo-form/create-photo-form.component.ts
> +
put the id of Працює status

2022-06-30 10:00 UTC, LeraKornienko approved these changes

2022-06-30 10:59 UTC, litvinets commented
it doesn't work. On update the status is sending as null, there should be an id 
![image](https://user-images.githubusercontent.com/27493959/176661354-ab7b4ec7-5170-42ff-8c16-17c7ed3ea7eb.png)

2022-06-30 11:00 UTC, litvinets requested changes
needs work

2022-06-30 11:00 UTC, litvinets commented on src/app/shared/constants/constants.ts
> +  static readonly INSTITUTION_STATUS_ID_ABSENT_VALUE = 1;
revrt this change, thr absent value should be remained as null

2022-07-01 20:44 UTC, litvinets requested changes
Freezed until the back-end is ready

2022-07-11 12:04 UTC, sivxkxn approved these changes
Wrote a comment related class of Constants, but the PR is good.

2022-07-12 17:22 UTC, sivxkxn commented on src/app/shell/personal-cabinet/provider/create-provider/create-photo-form/create-photo-form.component.ts
> +    this.institutionStatuses$.pipe(takeUntil(this.destroy$),filter((institutionStatuses: InstitutionStatus[])=>(!!institutionStatuses))).subscribe((institutionStatuses: InstitutionStatus[]) => {
formmating

2022-07-14 08:49 UTC, litvinets approved these changes

2022-07-14 11:59 UTC, merged

2022-07-14 11:59 UTC, Illya97 commented
Fixed