About portal, Support, Rules
ita-social-projects/OoS-Frontend pull request #1420
Opened 2022-07-05 10:16 UTC by sivxkxn

#1292

2022-07-05 15:54 UTC, litvinets reviewed
use state please

2022-07-05 15:59 UTC, litvinets requested changes
can you please fix a bit of styling? It should be the same as before 
![image](https://user-images.githubusercontent.com/27493959/177368269-297d532c-6294-4a31-b08a-e5f09d1d1efb.png)
![image](https://user-images.githubusercontent.com/27493959/177368305-6f9fc797-89dd-42fb-8dad-d6a8c8e6b359.png)

2022-07-05 16:03 UTC, litvinets requested changes
Please, can you additionally add routing back on successful update 
Currently the routing is broken 
![image](https://user-images.githubusercontent.com/27493959/177369837-3a31d0ec-e1f1-4822-ae8a-0644eb304de8.png)

Err: polyfills.07a5c2670fe49c10aa0d.js:1 Unhandled Promise rejection: Cannot match any routes. URL Segment: 'admin-tools/platform/AboutPortal' ; Zone: <root> ; Task: Promise.then ; Value: Error: Cannot match any routes. URL Segment: 'admin-tools/platform/AboutPortal'

2022-07-06 13:44 UTC, sivxkxn commented
@litvinets 
1. replaced services with store;
2. added routing after Save changes;
3. left the styles as they were, the font of the text depends on the scale in the browser;
4. fixed build ;

2022-07-06 14:14 UTC, litvinets requested changes

2022-07-06 14:14 UTC, litvinets commented on src/app/shell/admin-tools/platform/platform-info/info-edit/info-edit.component.html
> +      <a [routerLink]="setRoute()"><button class="btn" mat-button type="submit"[disabled]="PlatformInfoItemArray.invalid || titleFormControl.invalid"  (click)="onSubmit()">Зберегти</button></a>
this.router.navigate([`/admin-tools/platform/`, { queryParams: {page: payload}}]); 
![image](https://user-images.githubusercontent.com/27493959/177571102-4d413a71-1c51-41f2-bfc7-6a5efe36c789.png)

2022-07-06 18:28 UTC, litvinets approved these changes

2022-07-06 19:56 UTC, sivxkxn commented on src/app/shell/admin-tools/platform/platform-info/info-edit/info-edit.component.html
> +      <a [routerLink]="setRoute()"><button class="btn" mat-button type="submit"[disabled]="PlatformInfoItemArray.invalid || titleFormControl.invalid"  (click)="onSubmit()">Зберегти</button></a>
done, but it is not working as expected

2022-07-07 12:17 UTC, litvinets requested changes

2022-07-07 12:17 UTC, litvinets commented on src/app/shared/store/admin.state.ts
> +    this.router.navigate([`/admin-tools/platform/`, { queryParams: {page: payload}}]);
instaed of payload pass type

2022-07-11 18:50 UTC, litvinets approved these changes

2022-07-11 19:06 UTC, merged