#1193 Block User
ita-social-projects/OoS-Frontend pull request #1431
Opened 2022-07-05 21:26 UTC by LeraKornienko

2022-07-06 13:24 UTC, litvinets reviewed
overall, there is an excellent job!! Well done, comments are related only to code style

2022-07-06 13:24 UTC, litvinets commented on src/app/shared/store/user.actions.ts
> +  constructor(public payload) { }
public payload: BlockedParent

2022-07-06 13:24 UTC, litvinets commented on src/app/shared/store/user.state.ts
> +
remove redundant line

2022-07-06 13:24 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.html
> +
remove redundant lines

2022-07-06 13:24 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.ts
> +        blockedParent = new BlockedParent( parent, provider.id, reason);
let's pass it directly to constructor, so we can remove additional value reason 
  blockedParent = new BlockedParent( parent, provider.id, result);

2022-07-06 13:24 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.ts
> +        const parent = this.application.parentId;
const parentId

2022-07-06 13:24 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.ts
> +        blockedParent = new BlockedParent( parent, provider.id, reason);
parentId

2022-07-06 13:24 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.ts
> +        console.log("reason2", reason)
remove?

2022-07-06 13:24 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.ts
> +        console.log("blockedParent",blockedParent)
remove?

2022-07-06 13:24 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.ts
> +        const parent = this.application.parentId;
parentId

2022-07-11 10:12 UTC, Pabloostr approved these changes

2022-07-11 12:07 UTC, sivxkxn requested changes
There are some minor comments, in general, the PR is good ;)

2022-07-11 14:22 UTC, litvinets requested changes

2022-07-11 14:22 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.ts
> +   * @param Application application
fix js doc according to the method

2022-07-11 14:22 UTC, litvinets commented on src/app/shell/personal-cabinet/cabinet-data/cabinet-data.component.ts
> +    protected actions$: Actions,
we are following the approach from documentation, there is an actual observable
![image](https://user-images.githubusercontent.com/27493959/178281963-7a7753f7-0d61-4b23-b21c-94abd17ccef1.png)
![image](https://user-images.githubusercontent.com/27493959/178283207-ec2d4f56-5e33-445f-8224-bf6e03459f34.png)

2022-07-11 14:22 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.html
> +          <!-- <app-status-info-card [application]="application" [blockedParent]="blockedParent" [status]="status"></app-status-info-card> -->
remove?

2022-07-11 14:22 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.html
> +
redundant line

2022-07-11 14:27 UTC, litvinets commented on src/app/shared/components/block-modal-window/block-modal-window.component.ts
> +  modalTitle = 'ЗАБЛОКУВАТИ';
create related task https://github.com/ita-social-projects/OoS-Frontend/issues/1447

2022-07-12 11:36 UTC, sivxkxn approved these changes

2022-07-12 11:38 UTC, merged