Return user to the home page after cancellation while registration
ita-social-projects/OoS-Frontend pull request #1434
Opened 2022-07-07 11:48 UTC by Illya97

Follow the link: https://github.com/ita-social-projects/OoS-Backend/issues/686

2022-07-07 13:48 UTC, litvinets requested changes

2022-07-07 13:48 UTC, litvinets commented on src/app/shell/personal-cabinet/provider/create-provider/create-provider.component.ts
> +            type: ModalConfirmationType.approveApplication,
![image](https://user-images.githubusercontent.com/27493959/177780048-ba840103-e33e-45e9-9793-8e83dbabd3ec.png)

2022-07-07 13:48 UTC, litvinets commented on src/app/shell/personal-cabinet/provider/create-provider/create-provider.component.ts
> +            type: ModalConfirmationType.approveApplication,
remove this condition

2022-07-09 12:52 UTC, litvinets requested changes

2022-07-09 12:52 UTC, litvinets commented on src/app/shell/personal-cabinet/provider/create-provider/create-provider.component.ts
> +  logout(){
let's rename this function to "onCancel" because we not really want o logout, we want cancel the registration

2022-07-09 12:52 UTC, litvinets commented on src/app/shell/personal-cabinet/provider/create-provider/create-provider.component.ts
> +
I think you can remove the subscription earlier and use the approach to take a snapshot
     const isRegistered = this.store.selectSnapshot(RegistrationState.user).isRegistered;
and then use this value for checking

2022-07-11 07:26 UTC, litvinets approved these changes

2022-07-11 11:56 UTC, sivxkxn approved these changes
Good job!

2022-07-11 15:41 UTC, merged

2022-07-11 15:41 UTC, Illya97 commented
Done