Achievements cards
ita-social-projects/OoS-Frontend pull request #1446
Opened 2022-07-10 18:20 UTC by Olya-web7

2022-07-11 07:57 UTC, litvinets requested changes
1) I think we should add three dots (as for workshop-title in workshop-card), to limit the achievement title 
![image](https://user-images.githubusercontent.com/27493959/178214806-d89cb84b-9596-470c-a8b8-e3219f7fbed0.png)
![image](https://user-images.githubusercontent.com/27493959/178214837-4cac7ade-58cc-4295-97c4-fdad8171e77b.png)
let's keep the achievement title max in two rows
2) limit the the description max for 2 rows, and display "more", then the card should me "opened" and display the fill possible info 
![image](https://user-images.githubusercontent.com/27493959/178215478-c5e90a12-7494-40d6-ab41-13abafde72aa.png)
3) add a margin between the achievement title and the content 
![image](https://user-images.githubusercontent.com/27493959/178215964-0059fc10-6337-47aa-a3b3-9ecbc465a9b7.png)
4) add a banner to add new achievement from the details (it is not very difficult and in addition we will finish the view of the details)  
![image](https://user-images.githubusercontent.com/27493959/178216068-9233c78b-9210-47be-9c70-49af34324923.png)
5) I am unsure if it is included in this PR, but the delete doesn't work correctly. The request fails/does not finish its loading, but this fix can be included to another PR

2022-07-11 07:57 UTC, litvinets commented on src/app/shell/details/achievements/achievements.component.scss
> +  min-width: 500px;
let's keep it according to teh designs 
![image](https://user-images.githubusercontent.com/27493959/178214388-3fad43fc-df49-487b-b4ab-82843f053f0a.png)
![image](https://user-images.githubusercontent.com/27493959/178214415-3b3f2558-cc58-4515-8597-78733b5e73f0.png)

2022-07-11 07:57 UTC, litvinets commented on src/app/shell/personal-cabinet/provider/create-achievement/create-achievement.component.html
> -        </app-validation-hint> TODO: validation-->
why?

2022-07-12 18:50 UTC, sivxkxn requested changes

2022-07-12 18:50 UTC, sivxkxn commented on src/app/shared/store/user.actions.ts
> +  constructor(public payload) { }
can you please add type for the payload

2022-07-12 18:50 UTC, sivxkxn commented on src/app/shell/details/achievements/achievements.component.scss
> +// .description {
please delete the commented styles

2022-07-14 08:51 UTC, litvinets commented
![image](https://user-images.githubusercontent.com/27493959/178943061-1d30e5fa-5935-4405-8af6-9a20f4217eea.png)

2022-07-14 08:51 UTC, litvinets commented
there are errors if you are not registered 
![image](https://user-images.githubusercontent.com/27493959/178943188-e9c221af-727e-4632-a419-11190a1cf758.png)

2022-07-14 09:47 UTC, sivxkxn requested changes

2022-07-14 09:47 UTC, sivxkxn commented on src/app/shared/store/user.state.ts
> +  ): Observable<object> {
Are you sure is the type an object? Can you please specify

2022-07-14 09:47 UTC, sivxkxn commented on src/app/shared/services/achievements/achievements.service.ts
> +  deleteAchievement(id: string): Observable<object> {
Are you sure is the type an object? Can you please specify

2022-07-14 09:47 UTC, sivxkxn commented on src/app/shell/details/achievements/achievements.component.html
> +{{workshops | async | json}}
Is there really a need to output the workshops as objects in raw form to the template?

2022-07-14 09:47 UTC, sivxkxn commented on src/app/shell/details/achievements/achievements.component.ts
> +  @Select(UserState.workshops) workshops: Observable<any[]>;
please try to avoid type any. it breaks the concept of TypeScript

2022-07-14 09:47 UTC, sivxkxn commented on src/app/shared/store/user.actions.ts
> +  constructor(public payload) { }
Please add a type

2022-07-15 08:09 UTC, sivxkxn requested changes
Good work but also had some comments mostly related to types

2022-07-15 08:09 UTC, sivxkxn commented on src/app/shell/details/achievements/achievements.component.html
> +<!-- {{workshops | async | json}} -->
remove comments please

2022-07-15 08:09 UTC, sivxkxn commented on src/app/shell/details/achievements/achievements.component.ts
> +  getWorkshopIds(arr) {
please add types for arr and for returned result of the function

2022-07-15 08:09 UTC, sivxkxn commented on src/app/shell/details/achievements/achievements.component.ts
> +    let res = []
there is better to use const instead of let

2022-07-15 08:09 UTC, sivxkxn commented on src/app/shell/details/achievements/achievements.component.ts
> +    arr.forEach((i) => res.push(i.workshopId));
please provide types for i and for returned result of the function

2022-07-18 09:14 UTC, litvinets commented
![image](https://user-images.githubusercontent.com/27493959/179480598-f4aafc1e-7da5-4013-9a50-6e2c237e92b0.png)

2022-07-18 09:15 UTC, litvinets requested changes
something is wrong 
![image](https://user-images.githubusercontent.com/27493959/179480773-bd2ac163-3711-4119-9afc-4f7001172eba.png)

2022-07-18 09:17 UTC, litvinets commented
there something terrible in the network (to mich same requests)
![image](https://user-images.githubusercontent.com/27493959/179481191-664481b9-29ed-4bc4-9119-0960ca7e5e9c.png)

2022-07-20 12:34 UTC, litvinets requested changes

2022-07-20 12:34 UTC, litvinets commented on src/app/shared/components/achievement-card/achievement-card.component.html
> +                  {{child.firstName}} {{child.lastName}} {{child.middleName}}
apply please Util.getFullName

2022-07-20 12:34 UTC, litvinets commented on src/app/shared/components/achievement-card/achievement-card.component.ts
> +  readonly achievementsTitle = AchievementsTitle;
move readonly to the top

2022-07-20 12:34 UTC, litvinets commented on src/app/shared/components/achievement-card/achievement-card.component.ts
> +  readonly achievementsTitle = AchievementsTitle;
add empty rows between input, select, public fields

2022-07-20 12:34 UTC, litvinets commented on src/app/shared/components/achievement-card/achievement-card.component.ts
> +    return res;
add typo everywhere

2022-07-20 12:34 UTC, litvinets commented on src/app/shell/details/achievements/achievements.component.html
> +
remove empty rows

2022-07-20 12:34 UTC, litvinets commented on src/app/shell/details/achievements/achievements.component.html
> +  <app-achievement-card *ngFor="let achievement of achievements"
align it in one row please

2022-07-20 12:34 UTC, litvinets commented on src/app/shell/details/achievements/achievements.component.ts
> +  showMore = false;
I think you din;t need thsi enymore

2022-07-20 12:34 UTC, litvinets commented on src/app/shell/details/achievements/achievements.component.html
> +<div *ngIf="auth" class="add-wrapper">
auth &&  workshop.providerId= provider.id
(you can add a new achievements to the workshop only this workshop belongs to your provider)

2022-07-20 12:34 UTC, litvinets commented on src/app/shared/components/achievement-card/achievement-card.component.ts
> +  provider: Provider;
instead of getting this data again, you can pass it as input

2022-07-20 12:34 UTC, litvinets commented on src/app/shared/components/achievement-card/achievement-card.component.ts
> +    return res;
too complicated checking for such functionality
it is enough to check achievement provider id with current user id, you can get this data if you pass it as input from workshop-details

2022-07-20 12:34 UTC, litvinets commented on src/app/shared/components/achievement-card/achievement-card.component.html
> +                {{(showMore) ? achievement.title : achievement.title | slice:0:150}}
good job:) I like it!

2022-07-20 12:34 UTC, litvinets commented on src/app/shared/store/user.state.ts
> +      tap((res) => dispatch(new OnDeleteAchievementSuccess(res))),
add typo please HttpReponse

2022-07-21 11:03 UTC, litvinets requested changes
fix some small issues

2022-07-21 11:03 UTC, litvinets commented on src/app/shared/models/achievement.model.ts
> +  children?: Child[];
I think these are required fields

2022-07-21 11:03 UTC, litvinets commented on src/app/shell/details/achievements/achievements.component.ts
> +    }
I think check of workshop si redundant, because workshop always gonna be

2022-07-21 11:03 UTC, litvinets commented on package.json
> +    "angular-read-more": "^1.0.7",
revert this chaneg please

2022-07-25 11:09 UTC, litvinets approved these changes

2022-07-25 13:25 UTC, sivxkxn approved these changes
Good job!
but also you still have one place with type 'object' can you please replace with certain type?
deleteAchievement(id: string): Observable< object >

2022-07-26 05:31 UTC, litvinets approved these changes

2022-07-26 09:53 UTC, merged