[Add child] Multiple selection is not possible from the 'Cоціальна група' drop-down list #859
ita-social-projects/OoS-Frontend pull request #1451
Opened 2022-07-11 16:25 UTC by Pabloostr

#859

2022-07-12 09:10 UTC, litvinets requested changes

2022-07-12 17:25 UTC, litvinets commented
1. remove required
2. checkboxes should be enabled for removing
3. fix data sending (it should be an array of objects)
4. if 'none' is selected, then only others should not be available for selection

2022-07-12 18:08 UTC, sivxkxn requested changes
Data types and semicolon should be fixed

2022-07-22 09:04 UTC, litvinets approved these changes

2022-07-22 12:28 UTC, sivxkxn approved these changes
SO GOOD JOB!

2022-07-22 12:28 UTC, merged