#1453 block reason
ita-social-projects/OoS-Frontend pull request #1463
Opened 2022-07-13 09:48 UTC by LeraKornienko

2022-07-13 10:06 UTC, sivxkxn approved these changes
Small comments, but in general good

2022-07-13 10:06 UTC, sivxkxn commented on src/app/shell/personal-cabinet/applications/application-card/info-status/info-status.component.ts
> +  destroy$:Subject<boolean>=new Subject<boolean>();
formatting

2022-07-13 10:06 UTC, sivxkxn commented on src/app/shell/personal-cabinet/applications/application-card/info-status/info-status.component.ts
> +  constructor(public store: Store,) { }
remove a comma

2022-07-13 10:06 UTC, sivxkxn commented on src/app/shell/personal-cabinet/applications/application-card/info-status/info-status.component.ts
> +  // this.store.dispatch(new OnClearBlockedParents())
remove commented code please

2022-07-13 10:06 UTC, sivxkxn commented on src/app/shell/personal-cabinet/applications/application-card/info-status/info-status.component.ts
> +        filter((blockedParent:BlockedParent)=>!!blockedParent))
also formatting

2022-07-14 08:56 UTC, litvinets commented
wrong status 
![image](https://user-images.githubusercontent.com/27493959/178944163-194298ab-2899-4539-9a8b-0b21e909c4eb.png)

2022-07-14 08:58 UTC, litvinets requested changes

2022-07-14 08:58 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/info-status/info-status.component.scss
> +        margin: 1rem 0 0 0;
I belive tehre are too much redundant styles, pleas,e consider to rewrite them and add only those that are needed

2022-07-14 21:53 UTC, Olya-web7 approved these changes

2022-07-18 08:53 UTC, merged

2022-07-18 08:54 UTC, litvinets requested changes

2022-07-18 08:54 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/info-status/info-status.component.html
> +        <div>
this element is redundant, remove it, please

2022-07-18 08:54 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/info-status/info-status.component.html
> +            <p *ngIf="reason" class="application-info-menu">{{reason}}</p>
fix aligment

2022-07-18 08:54 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/info-status/info-status.component.ts
> +
remove this empty line

2022-07-18 08:54 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.ts
>        workshopsId: []
I see you have this **. but I don't see why? Why do you need this value? Remove it if it is not used

2022-07-18 08:54 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.ts
>        workshopsId: []
same for ReasonFormGroup

2022-07-18 08:54 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.ts
>        workshopsId: []
also remove please subrole and its subscription, because it is not used as well