Feature/#146 changed cascading select
ita-social-projects/OoS-Frontend pull request #151
Opened 2021-04-13 18:25 UTC by NabokinAlexandr

2021-04-14 10:18 UTC, dmitryy90 requested changes

2021-04-14 10:18 UTC, dmitryy90 commented on src/app/shared/components/hobby-select/hobby-select.component.ts
> +  getDirections(data: iData[]): void {
add annotations

2021-04-14 16:55 UTC, NabokinAlexandr commented on src/app/shared/components/hobby-select/hobby-select.component.ts
> +  getDirections(data: iData[]): void {
Done

2021-04-15 08:59 UTC, dmitryy90 approved these changes

2021-04-15 09:06 UTC, merged