Get Achievements types from backend
ita-social-projects/OoS-Frontend pull request #1512
Opened 2022-07-26 19:20 UTC by Olya-web7

2022-07-27 12:15 UTC, sivxkxn approved these changes
Really good

2022-07-27 15:22 UTC, Pabloostr approved these changes

2022-07-28 07:34 UTC, litvinets requested changes
Please, apply it to the form! 
![image](https://user-images.githubusercontent.com/27493959/181448121-acf39cca-b8c2-42d7-8693-cedc9eea6ed8.png)

2022-07-28 07:34 UTC, litvinets commented on src/app/shared/services/achievements/achievements.service.ts
> +  getAchievementType(): Observable<AchievementType[]> {
getAchievementsType

2022-07-28 08:15 UTC, sivxkxn approved these changes

2022-07-28 11:31 UTC, litvinets commented
![image](https://user-images.githubusercontent.com/27493959/181495194-671e9d7b-f9ef-46c4-9132-4121b052cd38.png)

2022-07-28 13:06 UTC, litvinets requested changes

2022-07-28 13:06 UTC, litvinets commented on src/app/shell/personal-cabinet/provider/create-achievement/create-achievement.component.ts
> +    this.store.dispatch(new GetAchievementsType());
mode it to 7 line

2022-07-29 11:34 UTC, litvinets approved these changes

2022-07-29 11:38 UTC, merged