#1510 Strict Filtering
ita-social-projects/OoS-Frontend pull request #1548
Opened 2022-08-08 15:54 UTC by LeraKornienko

2022-08-09 08:37 UTC, litvinets requested changes
Overall, great job!!! Please fix some minor comments and ping me for approval!!! Well done, baby:)

2022-08-09 08:37 UTC, litvinets commented on src/app/shared/components/filters-list/working-hours/working-hours.component.ts
> +    .subscribe((val: boolean) => this.store.dispatch(new SetIsStrictWorkdays(val)));
aligment

2022-08-09 08:37 UTC, litvinets commented on src/app/shared/components/filters-list/working-hours/working-hours.component.ts
> +    .pipe(takeUntil(this.destroy$))
add  debounceTime(300), operator, so it will not trigger filter on every click

2022-08-09 08:37 UTC, litvinets commented on src/app/shared/models/workshop.model.ts
> +  isStrictWorkdays?: boolean;
why? I think this is redundant field

2022-08-09 09:49 UTC, adv1 commented on src/app/shared/components/filters-list/working-hours/working-hours.component.html
> +  <!-- <div class="check-boxes" fxLayout="column" fxLayoutAlign="start">
Do we neeed this commented code?

2022-08-09 13:08 UTC, litvinets commented
@LeraKornienko  it was approved to move this checkbox as on the picture 
![image](https://user-images.githubusercontent.com/27493959/183654802-450bba2b-62dc-458f-9623-f0c7b872ac0d.png)

2022-08-15 11:38 UTC, adv1 approved these changes

2022-08-15 14:29 UTC, litvinets approved these changes

2022-08-15 14:29 UTC, litvinets commented on src/app/shared/components/filters-list/working-hours/working-hours.component.ts
> +import { Direction } from 'src/app/shared/models/category.model';
redundant imports 
![image](https://user-images.githubusercontent.com/27493959/184654641-89b32cc7-94cd-43d1-9799-4b1f89487b07.png)

2022-08-15 22:46 UTC, sivxkxn approved these changes
Really good)

2022-08-15 22:46 UTC, sivxkxn commented on src/app/shared/services/workshops/app-workshop/app-workshops.service.ts
> +    if (false) { //temp mock for further migration to codeficator
I would even add TODO to not forget about it

2022-08-16 10:30 UTC, Pabloostr approved these changes

2022-08-17 11:02 UTC, merged