Feature/ys update provider table #1540
ita-social-projects/OoS-Frontend pull request #1575
Opened 2022-08-23 02:03 UTC by sivxkxn

#1540

2022-08-23 10:28 UTC, litvinets commented
1) status color 
![image](https://user-images.githubusercontent.com/27493959/186135478-605985bf-9896-498e-be97-34e464588c86.png)
2) this information should be open on the right side of the table (as it was before), can you please check it out? 
![image](https://user-images.githubusercontent.com/27493959/186135632-ab1c931d-5d35-4f7a-af7e-65b26830c273.png)

2022-08-23 10:29 UTC, litvinets requested changes

2022-08-23 10:29 UTC, litvinets commented on src/app/shell/admin-tools/data/provider-list/provider-list.component.html
> +  (itemsPerPageChange)="onItemsPerPageChange($event)">
aligment

2022-08-23 10:31 UTC, sivxkxn commented on src/app/shell/admin-tools/data/provider-list/provider-list.component.html
> +  (itemsPerPageChange)="onItemsPerPageChange($event)">
fixed

2022-08-23 14:19 UTC, litvinets commented
still not fixed 
![image](https://user-images.githubusercontent.com/27493959/186182401-ceedb1f5-834e-42cf-bb12-f80bb3404342.png)

2022-08-23 14:22 UTC, litvinets requested changes
![image](https://user-images.githubusercontent.com/27493959/186183197-89fb5b1e-fcb4-4350-a3b3-eac5902d9cc4.png)
expected view

2022-08-26 07:01 UTC, litvinets approved these changes

2022-08-26 07:03 UTC, merged