[Create Ministry Admin] Handle the error
ita-social-projects/OoS-Frontend pull request #1581
Opened 2022-08-25 07:48 UTC by Illya97

Follow the link: https://github.com/ita-social-projects/OoS-Frontend/issues/1580

2022-08-25 10:27 UTC, litvinets requested changes

2022-08-25 10:27 UTC, litvinets commented on src/app/shared/store/admin.state.ts
> +      : 'На жаль виникла помилка при створенні адміністратора міністерства';
На жаль, 

(coma is missed)

2022-08-25 10:27 UTC, litvinets commented on src/app/shared/store/admin.state.ts
> +      ? 'Перевірте введені дані. Адміністратор міністерства з такою електронною поштою вже існує'
Користувач*

2022-08-25 10:36 UTC, litvinets requested changes

2022-08-25 10:36 UTC, litvinets commented on src/app/shared/store/admin.state.ts
> +      ? 'Перевірте введені дані. Адміністратор міністерства з такою електронною поштою вже існує'
HttpErrors[payload.error]   ---> 'Перевірте введені дані. Адміністратор міністерства з такою електронною поштою вже існує'

2022-08-26 21:37 UTC, sivxkxn approved these changes

2022-10-28 15:23 UTC, closed without merging