[Support/ LawsAndRegulations/ AboutPortal] - no info displaying
ita-social-projects/OoS-Frontend pull request #1591
Opened 2022-08-28 09:47 UTC by koliapatskal

#1583 

* Added a app-no-result-card component to display a message

*Added new value NoResultTitle

*Removed css property that caused info to overlap breadcrumbs

2022-08-28 09:49 UTC, koliapatskal commented
Display information before deleting css property.

![image](https://user-images.githubusercontent.com/111123815/187067952-d2f7dbe1-7e40-4500-9ab8-fa40e2283c4a.png)

2022-08-28 12:04 UTC, litvinets requested changes
spmething is wrong with you branch, therfe should be an image before the content 
![image](https://user-images.githubusercontent.com/27493959/187073281-d1705fa3-3ba9-4050-bf0f-309b6faaef5b.png)
![image](https://user-images.githubusercontent.com/27493959/187073295-a7c0d179-b8e9-4d6b-90e2-30994bfdf9a4.png)

2022-08-28 12:04 UTC, litvinets commented on src/app/shell/info/about/about.component.ts
> +  readonly emptyList = NoResultsTitle.noInfo;
this is not the proper naming, change it to more suitable such as noData/noInfo

2022-08-28 12:04 UTC, litvinets commented on src/app/shell/info/about/about.component.ts
> +  readonly emptyList = NoResultsTitle.noInfo;
move read-only field to the very top (before platformInformation) so we will stay consistent we our code style. it's not a strict rule, just approach for our project

2022-08-29 09:08 UTC, litvinets approved these changes

2022-08-29 09:40 UTC, merged