#1545 child for admins
ita-social-projects/OoS-Frontend pull request #1599
Opened 2022-08-29 10:27 UTC by LeraKornienko

2022-08-29 15:28 UTC, litvinets requested changes
![image](https://user-images.githubusercontent.com/27493959/187236712-9bb4e398-6c05-48ab-b943-b06b43ba187b.png)
1) wrong table view
2) search does not work
3)

2022-08-29 15:28 UTC, litvinets commented on src/app/shared/enum/enumUA/tech-admin/users-tabs.ts
> +
revert these chanegs

2022-08-29 20:42 UTC, sivxkxn commented on src/app/shared/services/children/children.service.ts
> +    if(parameters){
formatting in the file

2022-08-29 20:42 UTC, sivxkxn commented on src/app/shared/services/children/children.service.ts
> +        if(parameters.tabTitle == "Батьки"){
=== instead of ==

2022-08-29 20:42 UTC, sivxkxn commented on src/app/shared/services/children/children.service.ts
> +        if(parameters.tabTitle == "Діти"){
the same here

2022-08-29 20:42 UTC, sivxkxn commented on src/app/shared/services/children/children.service.ts
> +  getChildrenForAdmin(paremeters, isParent?): Observable<ChildCards> {
please change spelling on "parameters" and add types for arguments

2022-08-29 20:42 UTC, sivxkxn commented on src/app/shared/services/children/children.service.ts
> +    const options = { params: this.setParams(paremeters, isParent), };
also spelling here

2022-08-29 20:42 UTC, sivxkxn commented on src/app/shared/services/children/children.service.ts
> +    if(isParent !== undefined){
I'm not sure about this check. I guess isParent should be false by default. @litvinets what do you think?

2022-08-30 12:23 UTC, litvinets approved these changes

2022-08-30 12:32 UTC, merged