#1589 Block/Reject reason
ita-social-projects/OoS-Frontend pull request #1632
Opened 2022-09-02 14:02 UTC by LeraKornienko

done

2022-09-05 08:41 UTC, litvinets requested changes

2022-09-05 08:41 UTC, litvinets commented on src/app/shared/pipes/reason-transform.pipe.ts
> +  name: 'reasonTransform'
bad naming, this pipe can be reused for different purposes, so it is better to rename it according to its functionality

2022-09-07 13:00 UTC, litvinets requested changes

2022-09-07 13:00 UTC, litvinets commented on src/app/shared/pipes/text-transform.pipe.ts
> +  name: 'textTransform'
Stillman naming?
You transform text into what?
The naming should reflect the purpose

2022-09-09 05:35 UTC, litvinets requested changes
you should rename the test file as well, right?

2022-09-09 05:39 UTC, litvinets commented
This pipe still does not work correctly, the words are sliced without "-" 
![image](https://user-images.githubusercontent.com/27493959/189279039-1cdd25f0-09fd-43e7-9b5e-484636b1f06f.png)

2022-10-27 11:14 UTC, LeraKornienko commented
link #1632

2022-10-27 11:58 UTC, litvinets approved these changes

2022-10-27 11:58 UTC, litvinets commented on src/app/shell/personal-cabinet/shared-cabinet/applications/application-card/application-card.component.spec.ts
> +
remove readundant line

2022-10-27 12:08 UTC, litvinets commented
❤️❤️❤️

2022-11-01 14:46 UTC, merged