[Notifications] - handle new type of notifications #1625
ita-social-projects/OoS-Frontend pull request #1648
Opened 2022-09-13 08:44 UTC by Illya97

Follow the link: https://github.com/ita-social-projects/OoS-Frontend/issues/1625

2022-09-13 14:02 UTC, litvinets requested changes

2022-09-13 14:02 UTC, litvinets commented on src/app/shared/components/notifications/notifications-list/notifications-list.component.html
> +          Набір у гурток {{notification.data?.title}} {{(notification.data.Status=='Open')? 'відкрито': 'призупинено'}}
use enum WorkhopStatus

2022-09-15 09:11 UTC, Illya97 commented
![image](https://user-images.githubusercontent.com/50924109/190364632-ee885a15-f0b4-45eb-ac3b-097ffd557275.png)

2022-09-15 10:52 UTC, litvinets requested changes

2022-09-15 10:52 UTC, litvinets commented on src/app/shared/models/notifications.model.ts
> +  Title: string;
I believe status is not a required field

2022-09-15 10:52 UTC, litvinets commented on src/app/shared/enum/enumUA/workshop.ts
> +export enum WorkshopStatusUkr {
WorkshopNotificationStatusUkr

2022-09-16 10:54 UTC, litvinets approved these changes

2022-09-16 11:27 UTC, merged