Replaced most any types with a specific type
ita-social-projects/OoS-Frontend pull request #1697
Opened 2022-10-03 08:48 UTC by koliapatskal

*Added FilterList model

*Added MessageBar model

*Updated Rate model

*Replaced any types with specific type

2022-10-03 13:31 UTC, Y-Taras requested changes

2022-10-03 13:31 UTC, Y-Taras commented on src/app/shared/components/image-form-control/image-form-control.component.ts
> +  onChange: FilesToVoid;
please move these  fields above ngoninit method, since these are instance fields, not methods.

2022-10-03 13:31 UTC, Y-Taras commented on src/app/shared/components/image-form-control/image-form-control.component.ts
> +  onTouched: VoidToVoid;
same here

2022-10-04 10:37 UTC, litvinets approved these changes

2022-10-04 14:24 UTC, Y-Taras approved these changes

2022-10-04 14:28 UTC, merged