Issue#1662 add functionality to change main info
ita-social-projects/OoS-Frontend pull request #1725
Opened 2022-10-10 12:05 UTC by koliapatskal

#1662 
* Added the ability to add/edit info about main page
* Removed the ability to add sections when editing the main page, since there is a limit of 1 section

2022-10-10 13:40 UTC, litvinets commented
@Illya97 can you locally check if this functionality works? If you approve this code, then @koliapatskal you can merge this PR

2022-10-11 08:30 UTC, Illya97 commented
![image](https://user-images.githubusercontent.com/50924109/195038325-c15016b0-9a14-420f-ba5f-0b8ffe18628a.png)
please complete the title "РЕДАГУВАННЯ ГОЛОВНА СТОРІНКА" 
and I think next to "Заголовок" you need to put a red star because this field is mandatory

2022-10-11 08:30 UTC, Illya97 commented on src/app/shell/admin-tools/platform/platform-info/info-edit/info-edit.component.ts
> +  isMainPage: boolean = false;
you don't need to initialize this value as false, because isMainPage by default is false

2022-10-11 10:59 UTC, litvinets requested changes
after successful create/update, it should navigate to main page tab 
![image](https://user-images.githubusercontent.com/27493959/195073107-2dd12601-0514-4f54-b146-dbe0a1a0ebca.png)

2022-10-12 09:59 UTC, litvinets approved these changes

2022-10-12 10:07 UTC, merged