Issue#1790 general styles
ita-social-projects/OoS-Frontend pull request #1798
Opened 2022-11-02 11:14 UTC by koliapatskal

#1790 

* Fixed search-bar icons style
* Fixed workshop details
* Fixed form
* The blue color menu has been changed to white.
* Fixed search-bar
* Fixed filters

* Also added a limit on the width of social groups for correct display on mobile phones
![image](https://user-images.githubusercontent.com/111123815/199475801-4084f5ed-754b-40dd-8665-293957b4ec4b.png)

2022-11-02 17:11 UTC, khrMykhailo approved these changes

2022-11-02 17:11 UTC, khrMykhailo commented on src/app/shell/personal-cabinet/parent/create-child/child-form/child-form.component.html
> +  [ngClass]="childrenAmount > 1 ? 'step-border' : ''"
[class.step-border]="childrenAmount > 1"

2022-11-03 09:54 UTC, litvinets requested changes
text should be bold 
![image](https://user-images.githubusercontent.com/27493959/199691480-2ed861a7-feba-471f-8ca9-a7d4ffcc78ac.png)
![image](https://user-images.githubusercontent.com/27493959/199691511-cb32cf41-1d3b-4a1c-801f-575aea66838d.png)

2022-11-03 09:54 UTC, litvinets commented on src/app/shared/components/filters-list/full-search-bar/full-search-bar.component.scss
> +.search ::ng-deep .mat-icon{
space before curly brackets

2022-11-03 09:58 UTC, litvinets requested changes

2022-11-03 09:58 UTC, litvinets commented on src/app/shell/personal-cabinet/parent/create-child/child-form/child-form.component.html
> +    *ngIf="childrenAmount > 1"
*ngIf="!!childrenAmount"

2022-11-07 08:33 UTC, litvinets approved these changes

2022-11-07 13:39 UTC, merged