[Localization] - apply localization for Personal Cabinet (Parent/Provider view) #1867
ita-social-projects/OoS-Frontend pull request #1892
Opened 2022-12-07 10:57 UTC by khrMykhailo

Localization has been provided for Nav, and for two tabs in personal information

2022-12-07 11:57 UTC, litvinets requested changes

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +  "EDPNOU": "EDPNOU",
EDRPOIPN : Unified State Register Code of Enterprises and Organizations of Ukraine

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +  "DISTRICT_OF_THE_CITY": "District of the city",
DISTRICT: City district

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +  "FULL_ORGANIZATION_NAME": "Full Organization Name",
ORGANIZATION_FULL_NAME: Organization full name

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +  "ITN": "ITN",
ITN - > IPN
individual tax number

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +  "TYPE_OF_INSTITUTION": "Type of institution",
INSTITUTION_ TYPE: Institution Type

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +  "TYPE_OF_ORGANIZATION": "Organization type",
"ORGANIZATION_TYPE": "Organization type",

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +      "ABOUT_PORTAL": "About portal",
About the portal

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +      "EDIT_ADMIN": "Edit admin",
"EDIT_ADMIN": "Edit administrator",

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +      "EDIT_INFORMATION_ABOUT_CHILD": "Edit information about child",
duplication

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +      "EDIT_INSTITUTION": "Edit institution",
"EDIT_PROVIDER": "Edit provider indormation",

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +      "INFORMATION_ABOUT_CHILD": "Information about child",
I think this si redundant and can be removed
use already existed INFORMATION_ABOUT_CHILDREN

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +      "INFORMATION_ABOUT_PROVIDER": "Information about provider",
"INFORMATION_ABOUT_PROVIDER": "Information about the provider",

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +      "MAIN_PAGE": "Main page",
duplication, I think we can use only one -> Main Page

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +      "NEW_WORKSHOP": "New workshop",
NEW_WORKSHOP -> I think this is a wrong translation
for navbar, it should Add new workshop

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +      "NORMATIVE_LEGAL_ACTS": "Normative legal acts",
remove this one and apply LAWS_AND_REGULATIONS

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +      "REQUEST_ON_WORKSHOP": "Request on workshop",
New workshop application

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +      "TOP_DESTINATION": "Top destination",
"TOP_DESTINATION": "Top destination",
 remove and use TOP DIRECTIONS

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +      "UPDATE_ADMIN": "Update admin",
do not use shorts, for translation it has to be the whole word -> administrator
don't use "update", stick with the one translation variant, in our case  EDIT

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +      "USER_INFO": "User info",
**do not use abbreviation for translation**
User information

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +      "UPDATE_DEPUTY_DIRECTOR": "Update deputy director",
"UPDATE_DEPUTY_DIRECTOR": "Update deputy director",
EDIT PROVIDER DEPUTY -> Edit provider deputy

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +  "ADD_ACHIEVEMENTS": "Add Achievements",
"ADD_ACHIEVEMENTS": "Add Achievements",
```suggestion
  "ADD_ACHIEVEMENT": "Add Achievement",
```

2022-12-07 11:57 UTC, litvinets commented on src/assets/i18n/en.json
> +  "ABBREVIATED_NAME_OF_THE_ORGANIZATION": "Abbreviated name of the organization",
ABBREVIATED_NAME_OF_THE_ORGANIZATION - bad naming

  "FULL_ORGANIZATION_NAME": "Повна назва організації",
  "SHORT_ORGANIZATION_NAME": "Скорочена назва організації",

2022-12-07 11:57 UTC, litvinets commented on src/app/shell/personal-cabinet/shared-cabinet/user-config/user-config.component.html
> +    <h4>{{ 'PASSWORD' | translate }}</h4>
please, teh kepp general tarnslation approach
change, update replace with edit

2022-12-07 13:58 UTC, khrMykhailo commented on src/assets/i18n/en.json
> +      "EDIT_INFORMATION_ABOUT_CHILD": "Edit information about child",
No, it was ADD_INF, not EDIT

2022-12-09 10:35 UTC, litvinets requested changes

2022-12-09 10:35 UTC, litvinets commented on src/assets/i18n/en.json
>        "NAME": "Name",
First name

2022-12-09 10:35 UTC, litvinets commented on src/assets/i18n/en.json
> +  "DATE_OF_BIRTH_OF_THE_MANAGER": "Date of birth of the manager",
"DIRECTOR_BIRTHDAY": "Date of birth of the director",

2022-12-14 13:10 UTC, litvinets commented
@khrMykhailo  I have fixed the comments above and merged the PR, so we can reuse all the amazing work you have done further for the next localization steps! Thank you!! ♥

2022-12-14 13:15 UTC, litvinets approved these changes

2022-12-14 13:16 UTC, merged