Admin tools - localization
ita-social-projects/OoS-Frontend pull request #2003
Opened 2023-02-01 10:43 UTC by litvinets

admin-tools tabs localization
admins component
statistics
history log
providers
users

2023-02-01 14:31 UTC, koliapatskal requested changes
In the admin component, tabs and the add button are not localized

![image](https://user-images.githubusercontent.com/111123815/216069588-b38c1aea-4571-4be5-9235-6f8c13a5df01.png)

2023-02-01 14:31 UTC, koliapatskal commented on src/assets/i18n/en.json
> +    "BLOCK": "BLock",
Please make the second letter lowercase

2023-02-01 14:31 UTC, koliapatskal commented on src/assets/i18n/uk.json
> +    "WORKSHOPS_YEAR": "За рік"
You forgot to add the translation WORKSHOPS_DAILY and WORKSHOPS_YEAR to the English version, please add

2023-02-01 14:31 UTC, koliapatskal commented on src/assets/i18n/en.json
>        "ACCEPTED": "Accapted",
Accapted -> Accepted

2023-02-01 20:31 UTC, litvinets commented
@koliapatskal thanks for the comments! 
admins component is localized in the another PR

2023-02-02 09:57 UTC, koliapatskal approved these changes

2023-02-02 09:57 UTC, koliapatskal commented on src/assets/i18n/uk.json
> +      "BLOCK": "Заклад заблокований"
Please, add BLOCK to en.json file

2023-02-02 12:35 UTC, merged