Oliinyk / 2093 Possibility to open workshop when there is no seats for
ita-social-projects/OoS-Frontend pull request #2155
Opened 2023-07-18 07:46 UTC by doliinyk

#2093 

Add modal for workshop seats lack case that offers to change seats number; also provided min seats number in workshop editing if seats are already taken or there are recruitment open (taken seats + 1).

2023-07-18 17:34 UTC, humanmantis requested changes

2023-07-18 17:34 UTC, humanmantis commented on src/app/shared/components/workshop-card/workshop-seats-lack-modal/workshop-seats-lack-modal.component.html
> +    >
Keep the bracket on the same line

2023-07-18 17:34 UTC, humanmantis commented on src/app/shared/components/workshop-card/workshop-card.component.ts
> +            new UpdateWorkshopStatus(
The previous formatting was much more compact

2023-07-18 17:34 UTC, humanmantis commented on src/app/shared/components/workshop-card/workshop-card.component.ts
> +    } else {
Missing spaces in formatting

2023-07-18 18:12 UTC, doliinyk commented on src/app/shared/components/workshop-card/workshop-card.component.ts
> +    } else {
Can you specify what spaces are you mean? There are already spaces on these lines, my formatter doesn't change these lines

2023-07-19 09:27 UTC, humanmantis approved these changes

2023-07-19 09:27 UTC, humanmantis commented on src/app/shared/components/workshop-card/workshop-card.component.ts
> +    } else {
Check it again. 
Everything is fine, I didn't notice that the parentheses above are closed

2023-07-19 09:32 UTC, merged