Oliinyk / 2152 Create workshop email validation
ita-social-projects/OoS-Frontend pull request #2166
Opened 2023-07-21 11:36 UTC by doliinyk

#2152 

Add email regex and email validator, replaced default Angular email validators with created validator.
Refactored regex patterns and validators.

2023-07-21 11:43 UTC, doliinyk commented
TODO: Write hint for new validator for `app-validator-hint` (now error hint is empty, just red margin of input there)

2023-07-24 15:23 UTC, humanmantis approved these changes

2023-07-24 15:25 UTC, humanmantis commented on src/assets/i18n/uk.json
> +      "INVALID_CHARACTERS": ", використовуйте будь-ласка тільки кирилицю",
This is unrelated to code, but grammatically more correct version is: `, використовуйте, будь ласка, тільки кирилицю`

2023-07-24 15:28 UTC, humanmantis requested changes

2023-07-24 15:28 UTC, humanmantis commented on src/app/shared/components/confirmation-modal-window/reason-modal-window/reason-modal-window.component.html
>      >
Keep on same line

2023-07-24 15:28 UTC, humanmantis commented on src/app/shell/personal-cabinet/parent/create-child/child-form/child-form.component.html
>    >
same

2023-07-24 17:50 UTC, humanmantis approved these changes

2023-07-24 17:59 UTC, merged