Made gender radio button checked by default
ita-social-projects/OoS-Frontend pull request #2190
Opened 2023-08-02 12:12 UTC by Ultrafiolet4

2023-08-02 16:07 UTC, humanmantis requested changes

2023-08-02 16:07 UTC, humanmantis commented on src/app/shell/personal-cabinet/shared-cabinet/user-config/user-config-edit/user-config-edit.component.html
> +              [value]="0"
can we use Male / Female instead of `value`?

2023-08-03 09:45 UTC, humanmantis requested changes

2023-08-03 09:45 UTC, humanmantis commented on src/app/shell/personal-cabinet/shared-cabinet/user-config/user-config-edit/user-config-edit.component.html
> +              [checked]="user.gender === 'Male'">{{ 'FORMS.CONTROL_VALUES.MALE' | translate }}</mat-radio-button>
Is it worth keeping this `checked` property? 
I think correct `value` for radio buttons (same as from backend) should work in that case.

2023-08-03 09:45 UTC, humanmantis commented on src/app/shell/personal-cabinet/shared-cabinet/user-config/user-config-edit/user-config-edit.component.html
> +              [value]="'Male'"
can be just `value="Male"`

2023-08-03 09:55 UTC, Ultrafiolet4 commented on src/app/shell/personal-cabinet/shared-cabinet/user-config/user-config-edit/user-config-edit.component.html
> +              [value]="'Male'"
i tried that and it blocked radio button logic

2023-08-03 14:50 UTC, humanmantis approved these changes

2023-08-03 15:28 UTC, merged