Oliinyk / Region and Area admins integration
ita-social-projects/OoS-Frontend pull request #2193
Opened 2023-08-03 11:46 UTC by doliinyk

2023-08-03 11:47 UTC, doliinyk commented
Also waiting from backend:
- fix fetching area admins by region admin (now return 400)
- filtering admins due to user institution/CATOTTG on backend

2023-08-03 11:53 UTC, doliinyk commented on src/app/shared/store/admin.actions.ts
> +  constructor(public payload: BlockProviderData, public parameters: ProviderParameters) {}
Not sure about this change

2023-08-14 15:37 UTC, humanmantis requested changes

2023-08-14 15:37 UTC, humanmantis commented on src/app/shared/store/registration.state.ts
> +          .pipe(tap((territorialCommunityAdmin: TerritorialCommunityAdmin) => patchState({ areaAdmin: territorialCommunityAdmin })));
Rename `territorialCommunityAdmin` to `areaAdmin` for consistency

2023-08-14 15:37 UTC, humanmantis commented on src/app/shell/admin-tools/admin-tools.guard.ts
> +export function isRoleAdmin(role: string): boolean {
Move these functions to utils

2023-08-14 15:37 UTC, humanmantis commented on src/app/shared/store/registration.state.ts
> +  areaAdmin: TerritorialCommunityAdmin;
You add `areaAdmin` here, but do not replace `territorialCommunityAdmin` below (line 216)

2023-08-14 19:06 UTC, humanmantis approved these changes

2023-08-14 19:15 UTC, merged