Oliinyk / Admin block provider number requring
ita-social-projects/OoS-Frontend pull request #2222
Opened 2023-08-29 14:36 UTC by doliinyk

Now blocking provider modal requires admin phone number for feedback.
It is how it looks:
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/68949838/ed76cd7a-b59b-4fad-9bd9-5ca73aced5ee)

2023-08-29 15:09 UTC, doliinyk commented
Also add displaying admin phone number for blocked provider:
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/68949838/41e7a625-6626-48e0-a7cf-521d03259779)

2023-08-30 04:59 UTC, doliinyk commented
Making it ready-to-review PR because backend improvements are not hard to do

2023-08-30 07:18 UTC, humanmantis commented
I don't remember how it was before, but there should probably be some kind of label for textarea before the asterisk

2023-08-30 07:25 UTC, humanmantis requested changes

2023-08-30 07:25 UTC, humanmantis commented on src/app/shared/components/confirmation-modal-window/reason-modal-window/reason-modal-window.component.html
> +                ng-focus="updateValue()"
`ng-focus` is used in AngularJS, use `(focus)` instead

2023-08-30 13:38 UTC, doliinyk commented
>

2023-08-30 13:38 UTC, doliinyk commented
> I don't remember how it was before, but there should probably be some kind of label for textarea before the asterisk

In deploy it is looks the same

2023-08-30 14:16 UTC, humanmantis commented
> > I don't remember how it was before, but there should probably be some kind of label for textarea before the asterisk
> 
> In deploy it is looks the same

Understood, but this is an area that could be improved in the future, because the empty line with an asterisk may not be clear to all users. It might be worth adding some kind of label, such as "Reason for blocking" or something similar.

2023-08-30 14:17 UTC, humanmantis approved these changes

2023-08-30 15:09 UTC, merged