Oliinyk / PR2198 Improvement/Fix
ita-social-projects/OoS-Frontend pull request #2223
Opened 2023-08-31 05:37 UTC by doliinyk

#2133 

Fixed issue when provider is trying to start chat with parent

2023-08-31 05:39 UTC, doliinyk commented on src/app/shell/personal-cabinet/provider/provider-applications/provider-applications.component.ts
> +    this.store.dispatch(new SetParent(application.parent));
Chat is working now, but have a doubt about such solution.
It is needed to have parent object (id, name) to start chat. So here it is dispatching to store using parent **in application**.

Maybe there is another approach or it is better to fetch parent from backend?

2023-09-11 16:34 UTC, humanmantis requested changes

2023-09-11 16:34 UTC, humanmantis commented on src/app/shell/personal-cabinet/shared-cabinet/messages/messages.component.ts
> +  workshops$: Observable<TruncatedItem[]>;
add access modifiers

2023-09-11 16:34 UTC, humanmantis commented on src/app/shell/personal-cabinet/shared-cabinet/messages/chat/chat.component.ts
> +    setTimeout(() => {
use `asyncScheduler` instead

2023-09-11 16:34 UTC, humanmantis commented on src/app/shell/personal-cabinet/shared-cabinet/messages/chat/chat.component.ts
> +          this.chatEl.nativeElement.scrollTop = 10;
add readonly variable for `10`

2023-09-11 16:34 UTC, humanmantis commented on src/app/shared/services/chat/chat.service.ts
> +  getChatRoomsForProviderByParentId(parentId: string): Observable<ChatRoom[]> {
add access modifiers for methods

2023-09-11 16:34 UTC, humanmantis commented on src/app/shared/services/chat/chat.service.ts
> +    return this.http.get<ChatRoom[]>(`/api/v1/ChatWorkshop/provider/chatroomsforparent/${parentId}`);
`/api/v1/ChatWorkshop` this part can be a variable e.g. `baseApiUrl` or something similar

2023-09-11 16:41 UTC, humanmantis requested changes

2023-09-11 16:41 UTC, humanmantis commented on src/app/shell/personal-cabinet/shared-cabinet/messages/chat/chat.component.ts
> +      this.chatEl.nativeElement.onscroll = () => {
use `addEventListener`, so we can call `removeEventListener` on destroy
another approach is Angular `Renderer2 tool

2023-09-12 20:50 UTC, humanmantis approved these changes

2023-10-13 07:31 UTC, merged