Fixed bug with same start and end time when creating a workshop, made input readonly
ita-social-projects/OoS-Frontend pull request #2250
Opened 2023-09-14 16:42 UTC by Ultrafiolet4

#2237

2023-09-14 17:29 UTC, humanmantis commented on src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/working-hours-form-wrapper/working-hours-form/working-hours-form.component.ts
> +    newHours = newHours % 24;
Here we can have 00:00, which is actually the beginning of the day.
So maybe in the case that start time is 23:59, end time should also be 23:59.

2023-09-14 17:29 UTC, humanmantis commented on src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/working-hours-form-wrapper/working-hours-form/working-hours-form.component.ts
> +      newHours = 23;
Here is vise versa

2023-09-14 17:29 UTC, humanmantis commented on src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/working-hours-form-wrapper/working-hours-form/working-hours-form.component.ts
> +    newHours = newHours % 24;
I don't think there will be any workshop that will be started on this time, so there is no problem with that.

2023-09-18 17:53 UTC, humanmantis requested changes

2023-09-18 17:53 UTC, humanmantis commented on src/app/shared/components/provider-info/provider-info.component.ts
> +
Why empty line here?

2023-09-18 17:53 UTC, humanmantis commented on src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/working-hours-form-wrapper/working-hours-form/working-hours-form.component.ts
Please add access modifiers to properties and methods in components where they have not been added before

2023-09-18 18:43 UTC, Ultrafiolet4 commented on src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/working-hours-form-wrapper/working-hours-form/working-hours-form.component.ts
Added, please check result.spec.ts, because i changed WorkshopFilterCard to WorkshopCard. I got an error with that, because of WorkshopFilterCard non-existence.

2023-09-18 20:14 UTC, humanmantis requested changes

2023-09-18 20:14 UTC, humanmantis commented on src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/working-hours-form-wrapper/working-hours-form/working-hours-form.component.ts
Thanks for adding to other files, but you forgot to add to this file)

2023-09-19 14:48 UTC, humanmantis approved these changes

2023-09-19 14:59 UTC, merged