Made confirmation modal for child edit save button
ita-social-projects/OoS-Frontend pull request #2257
Opened 2023-09-23 09:51 UTC by Ultrafiolet4

#2255

2023-09-25 21:01 UTC, humanmantis requested changes

2023-09-25 21:01 UTC, humanmantis commented on src/app/shell/personal-cabinet/parent/create-child/create-child.component.ts
> +    if (this.ChildrenFormArray.invalid && this.isDispatching) {
We do not need to do any work during dispatching

2023-09-26 11:15 UTC, Ultrafiolet4 commented on src/app/shell/personal-cabinet/parent/create-child/create-child.component.ts
> +    if (this.ChildrenFormArray.invalid && this.isDispatching) {
We discussed a similar problem in another place and decided that this condition should be checked

2023-09-28 12:25 UTC, humanmantis requested changes

2023-09-28 12:25 UTC, humanmantis commented on src/app/shell/personal-cabinet/parent/create-child/create-child.component.ts
> +    if (this.isDispatching) {
`!this.isDispatching` is probably correct version.

2023-09-28 13:13 UTC, humanmantis approved these changes

2023-09-28 13:28 UTC, merged