Bytsa/2244 info about provider when pressing the f5 button when editing information about the provider the page does not return to its previous state
ita-social-projects/OoS-Frontend pull request #2276
Opened 2023-10-07 17:46 UTC by Ultrafiolet4

#2244

2023-10-10 08:44 UTC, humanmantis commented
Have you tried this? https://www.ngxs.io/plugins/storage
We can store a part of our state in SessionStorage, and it allows us to keep everything under control in the NGXS State

2023-10-10 11:39 UTC, Ultrafiolet4 commented
No, I haven't. I think it doesn't matter here, we have the same sessionStorage by default.

2023-10-11 14:58 UTC, doliinyk commented
Fixed provider edit info page refresh issue & used NGXS Storage Plugin

2023-10-11 15:48 UTC, humanmantis requested changes

2023-10-11 15:48 UTC, humanmantis commented on src/app/shared/components/provider-info/provider-info.component.ts
> +  public constructor(private store: Store) {}
Remove access modifier for constructor

2023-10-11 15:48 UTC, humanmantis commented on src/app/shell/personal-cabinet/shared-cabinet/create-form/create-form.component.ts
> +  protected constructor(protected store: Store, protected route: ActivatedRoute, protected navigationBarService: NavigationBarService) {}
Remove access modifier for constructor

2023-10-11 15:48 UTC, humanmantis commented on src/app/shell/personal-cabinet/provider/create-provider/create-provider.component.ts
> +  public isEditMode: boolean = this.store.selectSnapshot(AppState.isEditMode);
Move selecting snapshot to ngOnInit

2023-10-11 16:15 UTC, humanmantis approved these changes

2023-10-11 16:19 UTC, merged