display an amount of chats with unread messages
ita-social-projects/OoS-Frontend pull request #2317
Opened 2023-11-27 16:34 UTC by SergeyGSA

2024-06-06 05:19 UTC, doliinyk commented
#2294

2024-06-08 22:59 UTC, doliinyk commented
Endpoint will be added and used by https://github.com/ita-social-projects/OoS-Backend/pull/1493

2024-06-12 05:44 UTC, doliinyk commented
https://github.com/ita-social-projects/OoS-Backend/issues/1491

2024-06-28 20:23 UTC, doliinyk commented
https://github.com/ita-social-projects/OoS-Backend/issues/1478

2024-07-02 20:11 UTC, humanmantis requested changes

2024-07-02 20:11 UTC, humanmantis commented on src/app/shared/components/notifications/notifications.component.ts
> +          if (payload.notificationType === NotificationType.Application) {
What if there is another type of notification? 
Probably an error will be thrown because we don't return an Observable

2024-07-02 20:11 UTC, humanmantis commented on src/app/shared/components/notifications/notifications.component.ts
> +        takeUntil(this.destroy$),
takeUntil should be the last operator

2024-07-02 20:11 UTC, humanmantis commented on src/app/shared/components/notifications/notifications.component.ts
> +        takeUntil(this.destroy$),
takeUntil should be the last operator

2024-07-02 20:11 UTC, humanmantis commented on src/app/shell/personal-cabinet/personal-cabinet.component.ts
> +      this.provider$
Can we use selectSnapshot instead?

2024-07-02 20:57 UTC, doliinyk commented
Together with merge also applied https://github.com/ita-social-projects/OoS-Frontend/commit/2772aadfb65a20f501b610a15c690963a5224251 fixes as mobile-specific since it was done according to mobile issue and was breaking other breakpoint styles

2024-07-09 07:38 UTC, humanmantis approved these changes

2024-07-09 08:00 UTC, merged