2324 service provider incorrect status of the save button when editing a provider properties
ita-social-projects/OoS-Frontend pull request #2330
Opened 2024-01-07 23:38 UTC by ValentinaDej

Resolved an issue where the Save button remained disabled during form edits due to programmatic field updates not triggering the form's 'dirty' state.

2024-01-08 15:19 UTC, humanmantis requested changes

2024-01-08 15:19 UTC, humanmantis commented on src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/create-about-form.component.html
>        >
Leave the closing brackets at the same line. 
There are few places in this file with same issue

2024-01-15 11:56 UTC, ValentinaDej commented on src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/create-about-form.component.html
>        >
fixed

2024-01-15 12:08 UTC, humanmantis approved these changes

2024-01-15 17:48 UTC, merged