Morozov restrict enter alpha letters 2045
ita-social-projects/OoS-Frontend pull request #2369
Opened 2024-02-05 13:43 UTC by vladmorozov2

Issue: (#2045 )

Added new directive which checks if input is date symbols and applied to datapicker

2024-02-05 16:59 UTC, humanmantis requested changes

2024-02-05 16:59 UTC, humanmantis commented on src/app/shared/directives/date-symbols-checker.directive.ts
Please reuse the KeyFilter directive, just pass it the appropriate RegExp from constants.

2024-02-06 08:39 UTC, vladmorozov2 commented
Made git pull and just used keyFilter with appropriate regexp.
Please review again

2024-02-06 19:41 UTC, humanmantis approved these changes

2024-02-09 09:54 UTC, merged