Oliinyk / Notifications fix and refactoring
ita-social-projects/OoS-Frontend pull request #2390
Opened 2024-02-23 19:01 UTC by doliinyk

#2286
#2350
#2351
#2379
#2380

- Refactored actions component & removed disabling of message button if workshop closed;
- Notification refactoring, notification button style fix, fixed provider list for techadmin;
- Add 0 amount notifications badge;
- Refactored provider-state, geolocation service, userconfig (displaying of middle name if present);
- Add readAll and deleteAll notifications;
- Refactored title for notification of workshop/provider;
- Refactored navigation of notification;
- Refactored notification declination;
- Add ProviderUnblock notification;
- Completed notificationDescriptionPipe;
- Some word spelling fixes in translations.

![image](https://github.com/ita-social-projects/OoS-Frontend/assets/68949838/4ee04ad6-77d2-4746-8ad5-63213befe0d4)
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/68949838/25175f6a-6456-4dbe-ac3c-51831187b7e0)
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/68949838/148f4c14-e74b-4264-9e5e-1c688b2bc357)
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/68949838/6cdaf562-0ed5-4a6d-bbfd-7531c4465212)
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/68949838/f03e64bb-fd96-4c86-8ebb-e4311fd5bac1)
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/68949838/afe6a1ce-fbf8-4c39-a03b-a19dba4d15b4)

2024-02-25 11:24 UTC, humanmantis requested changes

2024-02-25 11:24 UTC, humanmantis commented on .vscode/extensions.json
Is there a reason to delete this file?

2024-02-25 11:24 UTC, humanmantis commented on src/app/shared/components/notifications/notifications-list/notifications-list.component.ts
> +    this.notifications.forEach((notification) => (notification.readDateTime = new Date(Date.now())));
`new Date()` should work

2024-02-25 11:24 UTC, humanmantis commented on src/app/shared/components/notifications/notifications-list/notifications-list.component.ts
> +    for (const notificationGroupedByType of this.notificationsGroupedByType) {
It is better to use internal methods for iterations rather than for... loops, as they have better performance

2024-02-25 11:24 UTC, humanmantis commented on src/app/shared/components/notifications/notifications.component.html
> +  <div *ngIf="notificationsAmount$ | async as notificationsAmount"
Is it possible to reuse the `notificationsAmount` property from a component to avoid creating an additional subscription?

2024-02-25 11:24 UTC, humanmantis commented on src/app/shared/components/notifications/notifications.component.ts
> +    private changeDetector: ChangeDetectorRef,
As I've seen in previous PRs, we usually used `cdr' instead of this naming

2024-02-25 11:34 UTC, doliinyk commented on .vscode/extensions.json
Suprised that it's deleted, that hasn't to be like that

2024-02-26 16:44 UTC, humanmantis approved these changes

2024-02-26 16:55 UTC, merged