#2404 scrolling bug
ita-social-projects/OoS-Frontend pull request #2520
Opened 2024-05-09 19:08 UTC by MarianS23

added custom mat tooltip default options ,tooltip disappear after cursor leave trigger zone.

2024-05-13 18:08 UTC, humanmantis requested changes

2024-05-13 18:08 UTC, humanmantis commented on src/app/app.module.ts
> +    { provide: MAT_TOOLTIP_DEFAULT_OPTIONS, useValue: CustomMatTooltipDefaultOptions }
Do not provide this options globally

2024-05-15 07:57 UTC, MarianS23 commented on src/app/app.module.ts
> +    { provide: MAT_TOOLTIP_DEFAULT_OPTIONS, useValue: CustomMatTooltipDefaultOptions }
done

2024-05-16 10:54 UTC, humanmantis requested changes

2024-05-16 10:54 UTC, humanmantis commented on src/app/shared/constants/constants.ts
> +export const CustomMatTooltipDefaultOptions: MatTooltipDefaultOptions = {
Give it a more specific name. "Custom" is a very general word. Maybe something like "NoInteractTooltipOptions".

2024-05-17 07:45 UTC, humanmantis approved these changes

2024-05-17 07:52 UTC, merged