Feature/melnychenko#230checkbox address
ita-social-projects/OoS-Frontend pull request #258
Opened 2021-06-11 13:01 UTC by myroslav-melnychenko

checkbox created with a trick (needed research on check icon rendering issue)

2021-06-11 13:27 UTC, dmitryy90 commented
wrong target branch

2021-06-11 14:29 UTC, dmitryy90 requested changes

2021-06-11 14:29 UTC, dmitryy90 commented on src/app/shell/personal-cabinet/provider/create-provider/create-contacts-form/create-contacts-form.component.ts
> +    if(ob.checked === true) {
you can use short expression avoiding comparison boolean with boolean

2021-06-14 07:48 UTC, dmitryy90 approved these changes

2021-06-15 03:05 UTC, litvinets requested changes

2021-06-15 03:05 UTC, litvinets commented on src/app/shell/personal-cabinet/provider/create-provider/create-contacts-form/create-contacts-form.component.ts
> +    /*this.isSameAddressControl.valueChanges.subscribe((val)=>{
I believe this code should be updated. You can create a new FormControl (for tracking the checkbox is checked) and subscribe to these changes. The forEach method you can simplify and replace with use such methods as patchValue and resetValue from Reactive Form Groups.  
![image](https://user-images.githubusercontent.com/27493959/121986569-67ce4e80-cd9f-11eb-9a43-25cb4fbb985e.png)

![image](https://user-images.githubusercontent.com/27493959/121986527-52592480-cd9f-11eb-9bf1-a0c76fe02724.png)

2021-06-15 03:05 UTC, litvinets commented on src/app/shell/personal-cabinet/provider/create-provider/create-contacts-form/create-contacts-form.component.scss
> +.checkbox {
Please, get rid of these styles. We already have styles in the shared scss files. You need to add class " class="step-check-box". If you want to change it, please do it in the shared one, so we will have the same for all forms. 
![image](https://user-images.githubusercontent.com/27493959/121986694-a5cb7280-cd9f-11eb-9fc8-97739a7943a9.png)

2021-06-17 09:49 UTC, closed without merging