Smyk/2561 Pop-up message related to the status 'Accepted for selection' should contain the information about selection specified on the workshop page
ita-social-projects/OoS-Frontend pull request #2584
Opened 2024-06-20 19:16 UTC by AndriiSmyk

#2561 
- Created 'getWorkshopCompetitiveSelectionDescriptionById' method in UserWorkshopService
- Changed info-status template to show competitive selection description if user has applicationStatus AcceptedForSelection

2024-06-21 06:07 UTC, doliinyk commented on src/app/shell/personal-cabinet/shared-cabinet/applications/application-card/info-status/info-status.component.ts
> +    if (this.status && this.status.toString() === 'AcceptedForSelection') {
I suggest to use [enum](https://github.com/ita-social-projects/OoS-Frontend/blob/72fe3d8f03b6b1c427812979b63eab9c720850a4/src/app/shared/enum/statuses.ts#L27) here
```suggestion
    if (this.status === ApplicationStatuses.AcceptedForSelection) {
```

2024-06-23 14:08 UTC, humanmantis requested changes

2024-06-23 14:08 UTC, humanmantis commented on src/app/shell/personal-cabinet/shared-cabinet/applications/application-card/info-status/info-status.component.html
> +      <div *ngIf="ApplicationTitles[status]===ApplicationTitles.AcceptedForSelection" class="application-info-menu application-info-description-card">{{ competitiveSelectionDescription }}</div>
fix formatting inside ngIf

2024-07-02 20:11 UTC, humanmantis approved these changes

2024-07-02 20:16 UTC, merged