fix regexp to search field
ita-social-projects/OoS-Frontend pull request #2654
Opened 2024-11-27 15:22 UTC by Liuboff

Some Ukrainian letters and space symbol were added to the regular expression.

2024-11-27 19:20 UTC, humanmantis commented on src/app/shared/components/filters-list/searchbar/searchbar.component.ts
> +    Validators.pattern('^[A-Za-zА-Яа-яІіЇїЄєҐґ0-9`.,№"\'\\s]*$')
Please, move this pattern to regexp-constants

2024-11-28 08:47 UTC, Liuboff commented on src/app/shared/components/filters-list/searchbar/searchbar.component.ts
> +    Validators.pattern('^[A-Za-zА-Яа-яІіЇїЄєҐґ0-9`.,№"\'\\s]*$')
Done

2024-12-01 20:31 UTC, humanmantis requested changes

2024-12-01 20:31 UTC, humanmantis commented on src/app/shared/components/filters-list/searchbar/searchbar.component.ts
> +    const validValue = value?.replace(/[^A-Za-zА-Яа-яІіЇїЄєҐґ0-9`.,№"'\s]/g, '');
This can also be moved to the constants

2024-12-01 20:31 UTC, humanmantis commented on src/app/shared/components/filters-list/searchbar/searchbar.component.ts
> +  public searchRegex: RegExp = SEARCHBAR_REGEX;
There is no need to create add property for this constant, we can use it directly

2024-12-02 08:33 UTC, Liuboff commented on src/app/shared/components/filters-list/searchbar/searchbar.component.ts
> +    const validValue = value?.replace(/[^A-Za-zА-Яа-яІіЇїЄєҐґ0-9`.,№"'\s]/g, '');
Placed to SEARCHBAR_REGEX_REPLACE

2024-12-02 08:33 UTC, Liuboff commented on src/app/shared/components/filters-list/searchbar/searchbar.component.ts
> +  public searchRegex: RegExp = SEARCHBAR_REGEX;
Removed

2024-12-02 09:08 UTC, humanmantis approved these changes

2024-12-02 11:30 UTC, merged