Zhylka/legacy chips rewriting
ita-social-projects/OoS-Frontend pull request #2655
Opened 2024-11-28 14:02 UTC by MaxZhylka

Replaced MatLegacyChipModule,  replaced all chip-lists by chip-set. In the CreateDescriptionForm component, specifically updated mat-chip-list to mat-chip-grid to resolve test failures

2024-12-01 20:30 UTC, humanmantis requested changes

2024-12-01 20:30 UTC, humanmantis commented on src/app/shell/personal-cabinet/provider/create-workshop/create-description-form/create-description-form.component.html
> +    <mat-chip-grid #chipGrid>
It is better to use mat-chip-grid together with the input to follow the correct [interaction pattern](https://v16.material.angular.io/components/chips/overview#text-entry)

2024-12-01 20:30 UTC, humanmantis commented on src/app/shell/personal-cabinet/parent/create-child/child-form/child-form.component.ts
> +
remove empty  row

2024-12-02 12:42 UTC, MaxZhylka commented
I am not sure if ngModel needs to be set on mat-chip-grid (as shown in the docs), because we use reactive forms. So, I removed ngModel from the input and fixed the issue where the input remained disabled after adding 5 elements and then removing one.

2024-12-02 15:09 UTC, humanmantis requested changes

2024-12-02 15:09 UTC, humanmantis commented on src/app/shell/personal-cabinet/provider/create-workshop/create-description-form/create-description-form.component.html
> +        [ngClass]="{  'keywords-input': !keyWordsCtrl.value && keyWords$.value.length < 1  }"
remove extra whitespace after `{ `and before `}`

2024-12-02 15:09 UTC, humanmantis commented on src/app/shell/personal-cabinet/provider/create-workshop/create-description-form/create-description-form.component.ts
> +  public separatorKeysCodes = [13, 188]; // Enter and Comma
Import keycodes from `@angular/cdk/keycodes`

2024-12-02 15:09 UTC, humanmantis commented on src/app/shell/personal-cabinet/provider/create-workshop/create-description-form/create-description-form.component.ts
> +      this.disabledKeyWordsInput = keyWords.length >= 5;
create a private read-only property for max keywords instead of a magic number

2024-12-02 15:09 UTC, humanmantis commented on src/app/shell/personal-cabinet/provider/create-workshop/create-description-form/create-description-form.component.ts
> +  public keyWords$: BehaviorSubject<string[]> = new BehaviorSubject<string[]>([]);
Why do we need a subject in this case?
We can simply do checks inside the method or create a separate method to switch the input state

2024-12-02 15:09 UTC, humanmantis commented on src/app/shell/personal-cabinet/provider/create-workshop/create-description-form/create-description-form.component.ts
> +    const index = keyWords.indexOf(word);
`keyWords.includes()`

2024-12-03 19:28 UTC, humanmantis approved these changes

2024-12-04 10:25 UTC, merged