Shapoval/edit draft workshop
ita-social-projects/OoS-Frontend pull request #2666
Opened 2024-12-09 14:46 UTC by DimaShapoval

create action buttons for provider workshops

2024-12-09 18:58 UTC, doliinyk reviewed
Looks good!

2024-12-09 18:58 UTC, doliinyk commented on src/app/shared/components/workshop-card/workshop-card.component.html
> +        <ng-container>
Since we're not using conditional rendering here, can we remove `ng-container`?

2024-12-09 18:58 UTC, doliinyk commented on src/app/shared/styles/workshop-status.scss
> +    }
Let's reuse the styles with `open` and `close` too

2024-12-09 18:58 UTC, doliinyk commented on src/app/shell/details/details.component.ts
> +        this.currentProvider = currentProvider;
As we aren't doing particular logic with the state properties, could we leave the subscription only for required ones and pass other using `async` pipe in template?

2024-12-09 18:58 UTC, doliinyk commented on src/app/shell/details/workshop-details/workshop-details.component.ts
> +        return this.store.dispatch(new PublishWorkshop(this.workshop.providerId));
Just a note - it's not necessary to return the observable here

2024-12-09 21:58 UTC, humanmantis requested changes

2024-12-09 21:58 UTC, humanmantis commented on src/app/shell/details/workshop-details/workshop-details.component.ts
> +    dialogRef.afterClosed().subscribe((res) => {
use `filter` operator instead condition below

2024-12-09 21:58 UTC, humanmantis commented on src/app/shell/details/workshop-details/workshop-details.component.ts
> +  public onActionButtonClick(modalType: string): void {
let's create enum for modalType

2024-12-10 23:36 UTC, humanmantis requested changes

2024-12-10 23:36 UTC, humanmantis commented on src/app/shell/details/workshop-details/workshop-details.component.ts
> +        filter((res) => !!res),
filter(Boolean)

2024-12-10 23:38 UTC, humanmantis commented on src/app/shell/details/details.component.ts
> +  public currentProvider$: Observable<Provider>;
fix linter issue

2024-12-11 10:09 UTC, humanmantis approved these changes

2025-01-07 14:05 UTC, merged