Yakymiv/dark theme toggle
ita-social-projects/OoS-Frontend pull request #2672
Opened 2024-12-18 18:03 UTC by YakymivY

2024-12-28 17:57 UTC, humanmantis requested changes
As I understand it, customization of theme colors will be done in separate PRs?
We should probably avoid using custom colors and try to use the most relevant material variables instead

2024-12-28 17:57 UTC, humanmantis commented on src/app/header/header.component.scss
> +::ng-deep .light-theme .mat-mdc-slide-toggle,
Can we move the theme switcher to a separate component?

2024-12-28 17:57 UTC, humanmantis commented on src/app/app.component.ts
> +      this.isDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
Use the injection token to manipulate the window. I know there are a few other places where we have the same problem, but we can fix them later

Take a look at: https://www.npmjs.com/package/ngx-window-token

2024-12-29 15:35 UTC, YakymivY commented
To enable dark mode correctly we need to rewrite styles in bunch of components, as some of them are hardcoded or need adjustments. So it is another task

2024-12-31 11:11 UTC, humanmantis requested changes

2024-12-31 11:11 UTC, humanmantis commented on src/app/app.component.ts
> +    @Inject(WINDOW) private _window: Window
`_window` => `window`

2024-12-31 11:11 UTC, humanmantis commented on src/app/app.component.ts
> +  public switchMode(isDarkMode: boolean): void {
move all logic inside switcher component

2025-01-06 19:29 UTC, humanmantis requested changes

2025-01-06 19:29 UTC, humanmantis commented on src/app/app.component.ts
> +    // const savedTheme = localStorage.getItem('preferred-theme');
Do we need this code?

2025-01-06 19:29 UTC, humanmantis commented on src/app/app.component.ts
> +    return this.isDark ? 'dark-theme' : 'light-theme';
Can we move this part to onToggleChange as well? You can set this class for body element or for the entire document

2025-01-08 18:08 UTC, humanmantis approved these changes

2025-01-08 18:34 UTC, merged