Feature/#228 style dropdown options
ita-social-projects/OoS-Frontend pull request #285
Opened 2021-06-18 06:55 UTC by sivxkxn

Adding styles to the dropdown with categories.

2021-06-18 07:35 UTC, dmitryy90 requested changes

2021-06-18 07:35 UTC, dmitryy90 commented on src/app/shared/styles/create-form.scss
> + ::ng-deep .mat-option-text{
indentations

2021-06-18 07:35 UTC, dmitryy90 commented on src/app/shared/styles/create-form.scss
> + ::ng-deep .mat-option-text{
use some namespace class to avoid overriding other dropdowns

2021-06-19 11:10 UTC, dmitryy90 requested changes

2021-06-19 11:10 UTC, dmitryy90 commented on src/app/shared/styles/create-form.scss
> +    padding: 0;
indentations

2021-06-19 11:10 UTC, dmitryy90 commented on src/app/shared/styles/create-form.scss
> +::ng-deep #mat-select-6-panel {
not sure about this selector. seems it auto generated.

2021-06-23 04:07 UTC, litvinets commented on src/app/shared/components/category-select/category-select.component.html
> +<form [formGroup]="CategoryFormGroup" class="form-category">
why do you need this class?

2021-06-23 04:19 UTC, litvinets commented
Unfortunately, you still have mismatching with the design.
The expected result: 
![image](https://user-images.githubusercontent.com/27493959/123034785-dd1ace80-d3f2-11eb-9dd5-bd0dccf9d304.png)
The actual result:
![image](https://user-images.githubusercontent.com/27493959/123034749-c3798700-d3f2-11eb-8b96-a3355f795884.png)

1. Remove please the gray color on the selected option on both sides and the division line between options.
2. The dropdown for the first option should not cover the selection input, it should be moved below. The other two options work correctly. 
![image](https://user-images.githubusercontent.com/27493959/123035029-54506280-d3f3-11eb-8888-50faab4cfc60.png)

2021-06-24 08:11 UTC, dmitryy90 approved these changes

2021-06-24 12:41 UTC, litvinets approved these changes

2021-06-24 12:46 UTC, merged