fixed image preview
ita-social-projects/OoS-Frontend pull request #296
Opened 2021-06-22 16:08 UTC by myroslav-melnychenko

2021-06-22 18:47 UTC, dmitryy90 requested changes

2021-06-22 18:47 UTC, dmitryy90 commented on src/app/shared/components/image-form-control/image-form-control.component.html
> +        <mat-grid-tile  class="logo_button" *ngIf="selectedImages.length < imgMaxAmount || selectedImages.length === 0">
indentations

2021-06-22 18:47 UTC, dmitryy90 commented on src/app/shared/components/image-form-control/image-form-control.component.scss
> +  margin-bottom:0.3rem;
indentations

2021-06-22 18:47 UTC, dmitryy90 commented on src/app/shared/components/image-form-control/image-form-control.component.scss
> +        width: 95px;
use relative units

2021-06-22 18:56 UTC, litvinets commented
Unfortunately, this task is not completed. The result does not meet the expectations. It should look like this: 
![image](https://user-images.githubusercontent.com/27493959/122982681-d3b64580-d3a3-11eb-9c0a-db1982312998.png)

But currently, you did this: 
![image](https://user-images.githubusercontent.com/27493959/122982647-c7ca8380-d3a3-11eb-9426-30cc0cee91c2.png)

In addition, the delete icons should be acknowledged by the BA and designers. At least, I think it has to be improved (remove these gray borders, and probably the red color is too aggressive). It should be discussed. 
![image](https://user-images.githubusercontent.com/27493959/122982948-2263df80-d3a4-11eb-80e7-91418cfe2ea1.png)


In the row should be only 4 pictures that evenly stretched in the layout.  
![image](https://user-images.githubusercontent.com/27493959/122983272-7c64a500-d3a4-11eb-9570-754b9470e3cf.png)

Something happened to the limitation of pictures, for example in this case it should be only 10 pictures max, but not 13. Verify this bug, please.

2021-06-22 19:11 UTC, litvinets commented
I see that input for new pictures disappeared when you reach the limit, but if you already clicked on it you can still attach as many pictures as you want. So, this is a problem.

2021-06-22 19:16 UTC, litvinets requested changes

2021-06-22 19:16 UTC, litvinets commented on src/app/shared/components/image-form-control/image-form-control.component.scss
> +}
you can try using nesting
mat-icon{
  &:hover{ }
}

2021-06-30 11:34 UTC, dmitryy90 requested changes

2021-06-30 11:34 UTC, dmitryy90 commented on src/app/shared/components/image-form-control/image-form-control.component.ts
> +    if(window.innerWidth >= 500){
use media queries

2021-06-30 11:34 UTC, dmitryy90 commented on src/app/shared/components/image-form-control/image-form-control.component.ts
> +    if(event.target.innerWidth >= 500){
duplicated code

2021-07-05 12:51 UTC, closed without merging