created navigatinBar
ita-social-projects/OoS-Frontend pull request #303
Opened 2021-06-24 14:25 UTC by DenysIvashchenko

2021-06-24 15:47 UTC, litvinets commented on src/app/shared/shared.module.ts
> +    NavigationBarComponent
coma

2021-06-24 15:47 UTC, litvinets commented on src/app/shared/shared.module.ts
> +    NavigationBarComponent
coma

2021-06-24 15:47 UTC, litvinets commented on src/app/shell/personal-cabinet/parent/create-application/create-application.component.ts
> +      {name:'Головна', path:'/', isActive:true, disable:false},
probably it is better to create enum? Such as "MainPage", "TopWorkshops", etc.

2021-06-24 15:47 UTC, litvinets commented on src/app/shell/result/result.component.ts
> +    * This method create new Navigation button
add @param to the annotation

2021-06-25 07:39 UTC, dmitryy90 requested changes

2021-06-25 07:39 UTC, dmitryy90 commented on src/app/shared/components/navigation-bar/navigation-bar.component.scss
> +  .isActive {
we dont use camel case in class names

2021-06-25 07:39 UTC, dmitryy90 commented on src/app/shared/components/navigation-bar/navigation-bar.component.scss
> +  font-size: 13px;
please make sure if it works with various resolutions

2021-06-25 07:39 UTC, dmitryy90 commented on src/app/shared/components/navigation-bar/navigation-bar.component.ts
> +  @Select(NavigationState.getNavPath)
the naming is a little bit confusing. state sounds like action. use meaningful name

2021-06-25 07:39 UTC, dmitryy90 commented on src/app/shared/models/navigation.model.ts
> +export interface Nav {
do we use I in the interfaces name?

2021-06-25 07:39 UTC, dmitryy90 commented on src/app/shared/store/navigation.state.ts
> +  static getNavPath(state: NavStateModel): Nav[] {return state.navPath}
see my comment above regarding naming

2021-06-25 07:39 UTC, dmitryy90 commented on src/app/shared/models/navigation.model.ts
> +export interface Nav {
and use meaningful class name

2021-06-25 07:39 UTC, dmitryy90 commented on src/app/shared/store/navigation.state.ts
> +        patchState({
indenations

2021-06-25 07:39 UTC, dmitryy90 commented on src/app/shell/personal-cabinet/parent/create-application/create-application.component.ts
> +      {name:'Головна', path:'/', isActive:true, disable:false},
if main page is always presented in the path we may move it to the navigation component and attach to dispatched items

2021-06-25 07:39 UTC, dmitryy90 commented on src/app/shell/personal-cabinet/personal-cabinet.component.ts
> +      {name:'Головна', path:'/', isActive:true, disable:false},
same

2021-06-25 07:39 UTC, dmitryy90 commented on src/app/shell/result/result.component.ts
> +  creatNavPath(name:string, isActive: boolean, disable: boolean): Nav[] {
I can see that createNavPath is duplicated in each component, I believe it will be better to move it to the service

2021-06-30 11:18 UTC, dmitryy90 approved these changes

2021-06-30 13:42 UTC, merged