keyWords from objects to array of string type #300
ita-social-projects/OoS-Frontend pull request #319
Opened 2021-07-02 12:35 UTC by sivxkxn

2021-07-02 12:50 UTC, litvinets commented
You should get rid of:
1) meta-data action and states related to the KeyWord old functionality
![image](https://user-images.githubusercontent.com/27493959/124276652-c2f89300-db4c-11eb-81d4-75526a187f5e.png)
![image](https://user-images.githubusercontent.com/27493959/124276738-dad01700-db4c-11eb-96f8-82d7ef9233a5.png)
![image](https://user-images.githubusercontent.com/27493959/124276759-e1f72500-db4c-11eb-8fab-333781bedf4a.png)
![image](https://user-images.githubusercontent.com/27493959/124276773-e7ed0600-db4c-11eb-979a-6f7ad34e562b.png)

2)key-word service
![image](https://user-images.githubusercontent.com/27493959/124276859-06eb9800-db4d-11eb-87f7-ffa5f1c716f2.png)

3) key-word model
![image](https://user-images.githubusercontent.com/27493959/124276899-136ff080-db4d-11eb-96df-63f8cf40dfa4.png)

2021-07-02 12:57 UTC, litvinets requested changes

2021-07-02 12:57 UTC, litvinets commented on src/app/shared/models/workshop.model.ts
> +    this.keyWords=description.keyWords;
indentation :)

2021-07-05 07:40 UTC, dmitryy90 approved these changes

2021-07-05 08:50 UTC, litvinets commented on src/app/shell/personal-cabinet/provider/create-workshop/create-description-form/create-description-form.component.ts
> +  constructor(private formBuilder: FormBuilder, private store: Store) {
you do not need to inject store as well, so you can delete it

2021-07-05 08:51 UTC, litvinets approved these changes

2021-07-05 09:21 UTC, merged