pop-up on status
ita-social-projects/OoS-Frontend pull request #462
Opened 2021-09-10 14:35 UTC by sivxkxn

2021-09-11 12:02 UTC, dmitryy90 requested changes

2021-09-11 12:02 UTC, dmitryy90 commented on src/app/shared/enum/applications.ts
> +  'Усі',
lets discuss  how we can store all titles and descriptions to support multi languages

2021-09-11 12:02 UTC, dmitryy90 commented on src/app/shell/personal-cabinet/personal-cabinet.component.html
> +          <span class="application-pending"><img src="assets/icons/Pending.png">Очікує підтвердження</span>
why dont you use values from enum?

2021-09-12 12:14 UTC, litvinets requested changes

2021-09-12 12:22 UTC, litvinets commented
1. I believe that info-box should appear when you click on the info icon. Because when you accidentally hover over it, the pop-up covers half of the page. Also, it should not disappear when you stop hovering the info-icon, because otherwise to read all the info the user should not move the mouse. 
2. It should be placed in the application tab but not inside the personal-cabinet tabs.
![image](https://user-images.githubusercontent.com/27493959/132987232-7246ea4b-cc5e-4018-a4fa-4a642935f3bf.png)
![image](https://user-images.githubusercontent.com/27493959/132987239-f50db523-abdd-4b52-a510-73fae83e09b9.png)
3.The info icon should be placed in the right upper corner for parent, and 
![image](https://user-images.githubusercontent.com/27493959/132987323-3956568c-ea3f-4742-8cd3-b05df336edce.png) and for provider in the same place but before the check-box-dropdown 
![image](https://user-images.githubusercontent.com/27493959/132987356-5ae0880a-36e6-428e-86fc-cd197eb29d03.png)

2021-09-12 12:27 UTC, litvinets commented
1. don't use images for icons, always look for mat-icon!
2. You created an enum for application statuses, so use it in your component, otherwise, why do you need it?
3. I think we should create a separate component for this information and open it on hovering. Use it everywhere you need (both in the tab and in the application cards). For the card case, you can pass as input the status you need and display it in the info-box component. The other statuses can be hidden. In the case when you click on info-icon, you can show all statuses.

2021-09-13 08:36 UTC, dmitryy90 requested changes

2021-09-13 08:36 UTC, dmitryy90 commented on src/app/shell/workshop-details/workshop-page/reviews/reviews.component.ts
> +        this.approvedApplications = applications.filter((application: Application) => application.status = ApplicationStatus[3]))
magic number

2021-09-13 14:13 UTC, dmitryy90 requested changes

2021-09-13 14:13 UTC, dmitryy90 commented on src/app/shared/enum/applications.ts
> +export enum ApplicationStatusDescription {
please move dictionary enums to separate folder

2021-09-13 14:23 UTC, litvinets requested changes

2021-09-13 14:23 UTC, litvinets commented on src/app/shell/personal-cabinet/personal-cabinet.component.ts
> +// import { MatMenuTrigger } from '@angular/material/menu';
do we need this?

2021-09-13 14:23 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.scss
> +// }
remove please styling that is not used

2021-09-13 14:23 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/applications.component.html
> + <app-status-info ></app-status-info>
add pointer of hover

2021-09-17 06:50 UTC, dmitryy90 approved these changes

2021-09-17 06:57 UTC, litvinets approved these changes

2021-09-18 18:33 UTC, merged