Featur/ivashchenko#448 horizontal workshop
ita-social-projects/OoS-Frontend pull request #471
Opened 2021-09-21 10:12 UTC by DenysIvashchenko

<img width="293" alt="create" src="https://user-images.githubusercontent.com/71029756/134153271-bbb4d839-05ea-45cf-8b6c-ecc50d64698c.png">
<img width="896" alt="createDeskTop" src="https://user-images.githubusercontent.com/71029756/134153273-ead62c22-d251-44f8-8488-6738fb997d7b.png">
<img width="345" alt="mainView" src="https://user-images.githubusercontent.com/71029756/134153277-2b13bb19-0bc5-4278-aecc-d300baf8fb9a.png">
<img width="284" alt="mobileView" src="https://user-images.githubusercontent.com/71029756/134153280-f329bf63-6cbf-44b3-b4c8-54c2820385b5.png">

2021-09-21 10:23 UTC, dmitryy90 requested changes

2021-09-21 10:23 UTC, dmitryy90 commented on src/app/shared/components/workshop-card/workshop-card.component.scss
> +  .card-img {
indentations

2021-09-21 10:23 UTC, dmitryy90 commented on src/app/shared/components/workshop-card/workshop-card.component.scss
> +    margin-bottom: 0 !important;
you can avoid using important by adding additional selector to increase priority

2021-09-21 13:52 UTC, litvinets commented on src/app/shared/components/workshop-card/workshop-card.component.html
> +      <p class="card_text" [ngClass]="isCreateApplicationView ? 'hide': ''">
why should we hide this info?

2021-09-21 13:55 UTC, DenysIvashchenko commented on src/app/shared/components/workshop-card/workshop-card.component.html
> +      <p class="card_text" [ngClass]="isCreateApplicationView ? 'hide': ''">
because 3 cards are different

2021-09-21 14:13 UTC, litvinets approved these changes

2021-09-22 11:58 UTC, dmitryy90 approved these changes

2021-09-23 13:23 UTC, dmitryy90 approved these changes

2021-09-23 13:24 UTC, merged