Routes enhancements #616
ita-social-projects/OoS-Frontend pull request #643
Opened 2021-11-17 12:21 UTC by romandivonchuk

2021-11-17 12:57 UTC, litvinets requested changes
I see when you firstly navigate from the main page to the result component, there are no workshops (but you received it from back-end). Nevertheless, the state is empty. Check it out please

2021-11-17 12:57 UTC, litvinets commented on src/app/shared/components/map/map.component.ts
> +
can you delete these lines?

2021-11-17 12:57 UTC, litvinets commented on src/app/shared/components/map/map.component.ts
> +
delete this line as well

2021-11-17 12:57 UTC, litvinets commented on src/app/shared/components/map/map.component.ts
> +          }
it's redundant. I think it will work this way:
return ( lat === value.address.latitude && lng === value.address.longitude);

2021-11-17 12:57 UTC, litvinets commented on src/app/shell/result/result.component.ts
> +      }
this.currentView = params.param === 'map' ? this.viewType.map : this.viewType.data;

2021-11-17 12:57 UTC, litvinets commented on src/app/shell/result/result.component.ts
> +      }
this.router.navigate([`result/${value}`]);

2021-11-17 12:57 UTC, litvinets commented on src/app/shell/result/workshop-map-view-list/workshop-map-view-list.component.ts
> +
redundant lines

2021-11-17 12:57 UTC, litvinets commented on src/app/shell/result/workshop-map-view-list/workshop-map-view-list.component.ts
> +      .subscribe(filteredWorkshops => this.workshops = filteredWorkshops.entities);
add typo

2021-11-17 12:57 UTC, litvinets commented on src/app/shell/result/result.component.ts
> +      if (params.param === 'map') {
I see you have this.viewType.map, so use it instead comparing to the string  'map'

2021-11-17 13:08 UTC, litvinets requested changes

2021-11-17 13:08 UTC, litvinets commented on src/app/shared/components/map/map.component.ts
> +  constructor(private geolocationService: GeolocationService,private previousUrl: PreviousUrlService) { }
spacing before 'private'
rename please previousUrl to previousUrlService
`  constructor(private geolocationService: GeolocationService, private previousUrl: PreviousUrlService) { }
`

2021-11-17 13:08 UTC, litvinets commented on src/app/shared/components/map/map.component.ts
> +    this.selectedWorkshop$.pipe(takeUntil(this.destroy$)).subscribe(value => {
add typo and rename value to workshop
`.subscribe((workshop: Workshop)=> {`

2021-11-17 13:08 UTC, litvinets commented on src/app/shared/components/map/map.component.ts
> +        targetMarkers.forEach(targetMarker => {
add typo

2021-11-17 13:08 UTC, litvinets commented on src/app/shared/components/map/map.component.ts
> +          targetMarker.isSelected && targetMarker.marker.setIcon(this.selectedMarkerIcon);
I believe line 235 always will be true, right?

2021-11-17 13:08 UTC, litvinets commented on src/app/shared/components/map/map.component.ts
> +        })
;

2021-11-17 13:08 UTC, litvinets commented on src/app/shared/components/map/map.component.ts
> +      if ('/workshop-details/'+value.id === this.previousUrl.getPreviousUrl()) {
spacing `'/workshop-details/' + value.id`

2021-11-17 13:54 UTC, litvinets requested changes

2021-11-17 13:54 UTC, litvinets commented on src/app/shared/components/map/map.component.ts
> +          const {lat, lng} = workshopMarker.marker.getLatLng()
;

2021-11-17 13:54 UTC, litvinets commented on src/app/shared/components/map/map.component.ts
> +        const targetMarkers = this.workshopMarkers.filter((workshopMarker) => {
add typo for workshopMarker:)

2021-11-17 13:54 UTC, litvinets commented on src/app/shared/components/map/map.component.ts
> +        const targetMarkers = this.workshopMarkers.filter((workshopMarker) => {
add typo for workshopMarker:)

2021-11-17 13:54 UTC, litvinets commented on src/app/shared/services/previousUrl/previous-url.service.ts
> +  public getPreviousUrl(){
public getPreviousUrl(): string{

2021-11-17 13:54 UTC, litvinets commented on src/app/shell/result/result.component.ts
> +
remove redundant line

2021-11-17 13:54 UTC, litvinets commented on src/app/shell/result/result.component.ts
> +    this.route.params.subscribe(params => {
add typo please

2021-11-17 13:54 UTC, litvinets commented on src/app/shell/result/result.component.ts
> +
remove redundant line please

2021-11-17 13:54 UTC, litvinets commented on src/app/shell/result/result.component.ts
> +    this.store.dispatch(new GetFilteredWorkshops(value === this.viewType.map)).subscribe(() => this.router.navigate([`result/${value}`]))
;

2021-11-17 13:54 UTC, litvinets commented on src/app/shell/result/result.component.ts
> +    this.store.dispatch(new GetFilteredWorkshops(value === this.viewType.map)).subscribe(() => this.router.navigate([`result/${value}`]))
takeUntil?

2021-11-17 14:02 UTC, litvinets requested changes

2021-11-17 14:02 UTC, litvinets commented on src/app/shared/services/previousUrl/previous-url.service.ts
> +      if (event instanceof NavigationEnd) {
I guess you can add this filtering to the pipe

2021-11-17 14:04 UTC, litvinets commented on src/app/shared/components/map/map.component.ts
> +  setPrevWorkShopMarker() {
add return typo
setPrevWorkShopMarker() : void

2021-11-17 16:09 UTC, litvinets requested changes

2021-11-17 16:09 UTC, litvinets commented on src/app/shell/result/workshop-map-view-list/workshop-map-view-list.component.ts
> +      .pipe(takeUntil(this.destroy$), filter((filteredWorkshops) => !!filteredWorkshops))
.pipe(
  takeUntil(this.destroy$), 
  filter((filteredWorkshops) => !!filteredWorkshops)
)

2021-11-17 16:09 UTC, litvinets commented on src/app/shell/result/workshop-map-view-list/workshop-map-view-list.component.ts
>    @Input() public filteredWorkshops$: Observable<WorkshopFilterCard>;
@Select(FilterState.filteredWorkshops)
  filteredWorkshops$: Observable<WorkshopCard[]>;


typo is not the same as it is passed from parent-component.

2021-11-17 16:09 UTC, litvinets commented on src/app/shell/result/workshop-map-view-list/workshop-map-view-list.component.ts
> +      .pipe(takeUntil(this.destroy$), filter((filteredWorkshops) => !!filteredWorkshops))
If filteredWorkshops is an array, then add .length

2021-11-17 16:09 UTC, litvinets commented on src/app/shared/components/map/map.component.ts
>    @Output() setAddressEvent = new EventEmitter<Address>();
verify filteredWorkshops$ typo (seems like it is an array)

2021-11-18 20:43 UTC, litvinets commented on src/app/shared/components/map/map.component.ts
> +          this.workshopMarkers.map((workshopMarker: WorkshopMarker) => this.map.removeLayer(workshopMarker.marker));
why do u need to map each element but not just to use forEach?

2021-11-18 20:43 UTC, litvinets commented on src/app/shared/components/map/map.component.ts
> +    this.workshopMarkers.push({ marker, isSelected: false});
why did you delete this space?

2021-11-18 20:43 UTC, litvinets commented on src/app/shell/result/result.component.ts
> +      this.currentView = (params.param === this.viewType.map) ? this.viewType.map : this.viewType.data;
probably you can avoid this comparing. Just to   this.currentView = params.param ? I believe param is equal to viewType value

2021-11-18 20:43 UTC, litvinets commented on src/app/shell/result/workshop-map-view-list/workshop-map-view-list.component.ts
> +  isSelectedMarker: boolean = false;
typo is redundant

2021-11-18 20:43 UTC, litvinets commented on src/app/shell/result/workshop-map-view-list/workshop-map-view-list.component.ts
> +  workshopDetailsAnimationState: boolean = false;
typo is redundant (linter issue)

2021-11-19 12:23 UTC, dmitryy90 approved these changes

2021-11-19 12:23 UTC, dmitryy90 commented on src/app/shared/services/previousUrl/previous-url.service.ts
> +      .pipe(filter(event => event instanceof NavigationEnd))
unsubscription is not needed until service is provided in single module

2021-11-19 12:51 UTC, litvinets approved these changes

2021-11-19 12:53 UTC, merged