The date of birth of the child has been set in the format 'dd.MM.YYYY…
ita-social-projects/OoS-Frontend pull request #653
Opened 2021-11-17 16:01 UTC by gmakeev

…' during adding children to workshop.

2021-11-17 16:28 UTC, litvinets requested changes

2021-11-17 16:28 UTC, litvinets commented on src/app/shared/components/child-card/child-card.component.ts
> +  //@Input() application: Application;
why?

2021-11-17 16:28 UTC, litvinets commented on src/app/shared/components/child-card/child-card.component.html
> +            <mat-icon class="card_icon">calendar_today</mat-icon> {{child.dateOfBirth | date: 'dd.MM.YYYY'}} ({{ childAge }})
date: constants.SHORT_DATE_FORMAT

2021-11-17 16:28 UTC, litvinets commented on src/app/shared/components/person-card/person-card.component.html
> +  <p>{{card.dateOfBirth | date: 'dd.MM.YYYY'}}</p>
date: constants.SHORT_DATE_FORMAT

2021-11-17 16:28 UTC, litvinets commented on src/app/shared/utils/utils.ts
> +      (lastDigit === 1) ? ageString = 'рік' : (lastDigit > 1 && lastDigit < 5) ? ageString = 'роки' : ageString = 'років';
(lastDigit === 1 && year !== 11)

2021-11-18 08:07 UTC, dmitryy90 approved these changes

2021-11-18 10:48 UTC, litvinets approved these changes

2021-11-18 10:51 UTC, merged