fixed applications style and menu
ita-social-projects/OoS-Frontend pull request #655
Opened 2021-11-18 20:19 UTC by tiana25

2021-11-18 20:49 UTC, litvinets requested changes

2021-11-18 20:49 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/applications.component.html
> +            :'shortDate'}})</h3>
date: constants.SHORT_DATE_FORMAT

2021-11-18 20:49 UTC, litvinets commented on src/app/shell/personal-cabinet/workshops/workshops.component.html
> +        <h3 class='name'> {{ child.firstName }} {{ child.lastName }} {{ child.middleName }} ({{ child.dateOfBirth | date
double quotes

2021-11-18 20:49 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.html
> +    <div class='block1' fxLayout='column' fxLayoutAlign='start start'>
double qoutes

2021-11-18 20:49 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.html
> +    <div class='block2' fxLayout='column' fxLayoutAlign='start start'>
double qoutes

2021-11-18 20:49 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.html
> +        <div class="organization" fxLayout='row' fxLayoutAlign='center center' *ngIf="userRole === role.parent">
double qoutes

2021-11-18 20:49 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.html
> +        <div class="workshop-age" fxLayout='row' fxLayoutAlign='center center' *ngIf="userRole === role.parent">
double qoutes

2021-11-18 20:49 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.html
> +    <div class='block3' *ngIf="application" [matMenuTriggerFor]="menu" #trigger="matMenuTrigger" (mouseenter)="trigger.openMenu()"
double qoutes

2021-11-18 20:49 UTC, litvinets commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.html
> +  <mat-card-content class="card-block" fxLayout='column' fxLayoutAlign='start center'>
double qoutes

2021-11-19 08:53 UTC, dmitryy90 requested changes

2021-11-19 08:53 UTC, dmitryy90 commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.html
> +    <div class="block1" fxLayout="column" fxLayoutAlign="start start">
please use meaningful class names

2021-11-19 08:53 UTC, dmitryy90 commented on src/app/shell/personal-cabinet/applications/application-card/application-card.component.scss
> +  width: 120px;
did you try relative units? percents?

2021-11-19 08:53 UTC, dmitryy90 commented on src/app/shell/personal-cabinet/applications/applications.component.html
> +          <h3 class="name"> {{ child.firstName }} {{ child.lastName }} {{ child.middleName }} ({{ child.dateOfBirth | date: constants.SHORT_DATE_FORMAT }})</h3>
please use meaningful class names. child-name

2021-11-19 08:53 UTC, dmitryy90 commented on src/app/shell/personal-cabinet/personal-cabinet.component.scss
>  ::ng-deep .mat-tab-link {
potential risk of overriding styles in other components

2021-11-19 12:24 UTC, dmitryy90 approved these changes

2021-11-19 12:35 UTC, litvinets approved these changes

2021-11-19 12:36 UTC, merged