add registration dropdown
ita-social-projects/OoS-Frontend pull request #68
Opened 2021-02-21 19:08 UTC by Art-mimiron

#62

2021-02-22 12:22 UTC, dmitryy90 requested changes

2021-02-22 12:22 UTC, dmitryy90 commented on src/app/header/header.component.html
> +          Заклад позашкільної освіти
forward to register page

2021-02-26 10:31 UTC, dmitryy90 approved these changes

2021-03-08 22:17 UTC, Art-mimiron commented
outdate

2021-03-08 22:17 UTC, closed without merging