Tech admin cabinet
ita-social-projects/OoS-Frontend pull request #769
Opened 2022-01-14 16:11 UTC by tiana25

2022-01-18 10:41 UTC, litvinets requested changes

2022-01-18 10:41 UTC, litvinets commented on src/app/header/header.component.html
> +      <ng-container *ngIf="((user$ | async)?.role !== Role.techAdmin)">
I think it is better to do case-switching in this way: 
```suggestion
    <div *ngIf="((user$ | async)?.role !== Role.techAdmin) then UserView; else AdminView"></div>
    <ng-template #UserView></ng-template >
    <ng-template #AdminView></ng-template >
```

In this case, we check the role only once, in your case the role checking if happening twice, for techadmin and for not techadmin

2022-01-18 10:41 UTC, litvinets commented on src/app/shared/components/sidenav/sidenav.component.html
> +          <ng-container *ngIf="((user$ | async)?.role !== Role.techAdmin)">
same as previous comment

2022-01-18 10:41 UTC, litvinets commented on src/app/shared/store/admin.state.ts
> +    console.log('InfoAboutPortal is updated', payload);
I believe condole.log we should remove

2022-01-18 10:41 UTC, litvinets commented on src/app/shell/admin-tools/admin-tools.guard.ts
> +    return this.role$.pipe(filter((role: string) => !!role), map((role: string) => (role === Role.techAdmin)));
```suggestion
    return this.role$.pipe(filter((role: string) => role === Role.techAdmin), map((role: string) => (role === Role.techAdmin)));
```

2022-01-20 09:31 UTC, dmitryy90 requested changes

2022-01-20 09:31 UTC, dmitryy90 commented on src/app/shared/styles/cabinet.scss
> +  border-bottom: none;
indentations

2022-01-20 09:31 UTC, dmitryy90 commented on src/app/shared/styles/cabinet.scss
> +    opacity: 1;
I cant see where we change opacity. Why do we need set 1 here?

2022-01-20 09:31 UTC, dmitryy90 commented on src/app/shell/admin-tools/platform/support-edit/support-edit.component.ts
> +    // this.SupportFormArray.controls.forEach((form: FormGroup) => {});
if this code is still needed use TODO: comment

2022-01-21 12:11 UTC, dmitryy90 approved these changes

2022-01-21 12:21 UTC, litvinets approved these changes

2022-01-21 12:22 UTC, merged