fix bgcolor and size of toggled buttons
ita-social-projects/OoS-Frontend pull request #808
Opened 2022-01-26 08:50 UTC by kokole110

fix bgcolor of toggled buttons and size of 'price per lesson-month' button in create workshop
issue: https://github.com/ita-social-projects/OoS-Frontend/issues/799

I found out that commenting out some css properties works well for this task, but that properties are closely related to different toggle buttons throughout the application, so I tried to check every single page/form creation and haven't found any other unwanted changes in buttons appearance but to be safe I haven't deleted them, just commented out for now

2022-01-26 11:07 UTC, litvinets commented
don't think that these styles we will need because all toggle buttons should have the same design. So, I think you can delete it

2022-01-26 11:08 UTC, litvinets requested changes
don't think that these styles we will need because all toggle buttons should have the same design. So, I think you can delete it

2022-01-27 08:08 UTC, dmitryy90 approved these changes

2022-01-27 12:11 UTC, litvinets approved these changes

2022-01-27 12:38 UTC, merged