#4 create header, shell layout & route
ita-social-projects/OoS-Frontend pull request #9
Opened 2021-01-21 11:31 UTC by NabokinAlexandr

2021-01-21 12:18 UTC, DmyMi requested changes
Hello, please change target branch from `main` to `develop`.
Use the following [template](https://github.com/ita-social-projects/OoS-Frontend/blob/main/.github/PULL_REQUEST_TEMPLATE/develop.md) for description

2021-01-21 13:16 UTC, dmitryy90 requested changes

2021-01-21 13:16 UTC, dmitryy90 commented on src/styles.scss
> +body { margin: 0; font-family: Roboto, "Helvetica Neue", sans-serif; }
duplicated code

2021-01-21 16:15 UTC, NabokinAlexandr commented on src/styles.scss
> +body { margin: 0; font-family: Roboto, "Helvetica Neue", sans-serif; }
fixed in next commit

2021-01-22 12:03 UTC, dmitryy90 approved these changes

2021-01-22 12:56 UTC, DmyMi approved these changes

2021-01-22 14:21 UTC, merged