[Edit child] The 'ЗБЕРЕГТИ' button stays enabled when mandatory 'По-батькові' field is empty #962
ita-social-projects/OoS-Frontend pull request #974
Opened 2022-03-08 17:19 UTC by Olya-web7

[Edit child] The 'ЗБЕРЕГТИ' button stays enabled when mandatory 'По-батькові' field is empty #962

2022-03-09 11:00 UTC, litvinets requested changes

2022-03-09 11:00 UTC, litvinets commented on src/app/shell/personal-cabinet/parent/create-child/create-child.component.ts
> +      this.isEmpty = !!!(val[0].lastName) || !!!(val[0].firstName) || !!!(val[0].middleName);
!val[0].lastName
!val[0].firstName
!val[0].middleName

2022-03-09 11:02 UTC, litvinets commented on src/app/shell/personal-cabinet/parent/create-child/create-child.component.ts
> +      this.isEmpty = !!!(val[0].lastName) || !!!(val[0].firstName) || !!!(val[0].middleName);
wrong typo? Why val is boolean but has lastName, firstName?

2022-03-09 11:03 UTC, litvinets commented on src/app/shell/personal-cabinet/parent/create-child/create-child.component.ts
> +      this.isEmpty = !!!(val[0].lastName) || !!!(val[0].firstName) || !!!(val[0].middleName);
I think you should simplify is to !(val[0].lastName || val[0].firstName || val[0].middleName)

2022-03-09 15:21 UTC, litvinets requested changes

2022-03-09 15:21 UTC, litvinets commented on src/app/shell/personal-cabinet/parent/create-child/create-child.component.ts
>      ).subscribe((val: boolean) => {
change please typo

2022-03-11 08:00 UTC, dmitryy90 approved these changes

2022-03-14 07:57 UTC, dmitryy90 approved these changes

2022-03-14 09:19 UTC, litvinets approved these changes

2022-03-14 12:06 UTC, litvinets commented
link this issue please (https://github.com/ita-social-projects/OoS-Frontend/issues/965)

2022-03-14 12:27 UTC, litvinets commented
https://github.com/ita-social-projects/OoS-Frontend/issues/965

2022-03-18 17:58 UTC, merged